package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.ActiveItems;
import com.ppsea.ds.data.model.ActiveItemsExample;
import java.sql.SQLException;
import java.util.List;

public class ActiveItemsDAOImpl implements ActiveItemsDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public ActiveItemsDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public int countByExample(ActiveItemsExample example) throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "active_items.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public int deleteByExample(ActiveItemsExample example) throws SQLException {
	    int rows = sqlMapClient.delete(
	            "active_items.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    ActiveItems key = new ActiveItems();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "active_items.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public Integer insert(ActiveItems record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "active_items.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public Integer insertSelective(ActiveItems record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "active_items.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public List selectByExample(ActiveItemsExample example) throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "active_items.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public ActiveItems selectByPrimaryKey(Integer id) throws SQLException {
	    ActiveItems key = new ActiveItems();
	    key.setId(id);
	    ActiveItems record = (ActiveItems) sqlMapClient.queryForObject(
	            "active_items.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public int updateByExampleSelective(ActiveItems record,
            ActiveItemsExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "active_items.ibatorgenerated_updateByExampleSelective", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public int updateByExample(ActiveItems record, ActiveItemsExample example)
            throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "active_items.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public int updateByPrimaryKeySelective(ActiveItems record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "active_items.ibatorgenerated_updateByPrimaryKeySelective",
	            record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    public int updateByPrimaryKey(ActiveItems record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "active_items.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table active_items
     * @ibatorgenerated  Fri Apr 22 13:56:54 CST 2011
     */
    private static class UpdateByExampleParms extends ActiveItemsExample {
	    private Object record;

	    public UpdateByExampleParms(Object record, ActiveItemsExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}