package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.Area;
import com.ppsea.ds.data.model.AreaExample;
import java.sql.SQLException;
import java.util.List;

public class AreaDAOImpl implements AreaDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public AreaDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public int countByExample(AreaExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"area.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public int deleteByExample(AreaExample example) throws SQLException {
		int rows = sqlMapClient.delete("area.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Area key = new Area();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"area.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public Integer insert(Area record) throws SQLException {
		Object newKey = sqlMapClient.insert("area.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public Integer insertSelective(Area record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"area.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public List selectByExample(AreaExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"area.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public Area selectByPrimaryKey(Integer id) throws SQLException {
		Area key = new Area();
		key.setId(id);
		Area record = (Area) sqlMapClient.queryForObject(
				"area.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public int updateByExampleSelective(Area record, AreaExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"area.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public int updateByExample(Area record, AreaExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("area.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public int updateByPrimaryKeySelective(Area record) throws SQLException {
		int rows = sqlMapClient.update(
				"area.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	public int updateByPrimaryKey(Area record) throws SQLException {
		int rows = sqlMapClient.update(
				"area.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table area
	 * @ibatorgenerated  Thu Aug 12 11:51:13 CST 2010
	 */
	private static class UpdateByExampleParms extends AreaExample {
		private Object record;

		public UpdateByExampleParms(Object record, AreaExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}