package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.BuffRand;
import com.ppsea.ds.data.model.BuffRandExample;
import java.sql.SQLException;
import java.util.List;

public class BuffRandDAOImpl implements BuffRandDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public BuffRandDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public int countByExample(BuffRandExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("buff_rand.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public int deleteByExample(BuffRandExample example) throws SQLException {
        int rows = sqlMapClient.delete("buff_rand.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        BuffRand key = new BuffRand();
        key.setId(id);
        int rows = sqlMapClient.delete("buff_rand.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public Integer insert(BuffRand record) throws SQLException {
        Object newKey = sqlMapClient.insert("buff_rand.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public Integer insertSelective(BuffRand record) throws SQLException {
        Object newKey = sqlMapClient.insert("buff_rand.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public List selectByExample(BuffRandExample example) throws SQLException {
        List list = sqlMapClient.queryForList("buff_rand.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public BuffRand selectByPrimaryKey(Integer id) throws SQLException {
        BuffRand key = new BuffRand();
        key.setId(id);
        BuffRand record = (BuffRand) sqlMapClient.queryForObject("buff_rand.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public int updateByExampleSelective(BuffRand record, BuffRandExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("buff_rand.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public int updateByExample(BuffRand record, BuffRandExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("buff_rand.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public int updateByPrimaryKeySelective(BuffRand record) throws SQLException {
        int rows = sqlMapClient.update("buff_rand.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    public int updateByPrimaryKey(BuffRand record) throws SQLException {
        int rows = sqlMapClient.update("buff_rand.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table buff_rand
     *
     * @ibatorgenerated Thu Jan 03 10:59:05 CST 2013
     */
    private static class UpdateByExampleParms extends BuffRandExample {
        private Object record;

        public UpdateByExampleParms(Object record, BuffRandExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}