package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.BuffType;
import com.ppsea.ds.data.model.BuffTypeExample;
import java.sql.SQLException;
import java.util.List;

public class BuffTypeDAOImpl implements BuffTypeDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public BuffTypeDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public int countByExample(BuffTypeExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("buff_type.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public int deleteByExample(BuffTypeExample example) throws SQLException {
        int rows = sqlMapClient.delete("buff_type.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        BuffType key = new BuffType();
        key.setId(id);
        int rows = sqlMapClient.delete("buff_type.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public Integer insert(BuffType record) throws SQLException {
        Object newKey = sqlMapClient.insert("buff_type.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public Integer insertSelective(BuffType record) throws SQLException {
        Object newKey = sqlMapClient.insert("buff_type.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public List selectByExample(BuffTypeExample example) throws SQLException {
        List list = sqlMapClient.queryForList("buff_type.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public BuffType selectByPrimaryKey(Integer id) throws SQLException {
        BuffType key = new BuffType();
        key.setId(id);
        BuffType record = (BuffType) sqlMapClient.queryForObject("buff_type.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public int updateByExampleSelective(BuffType record, BuffTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("buff_type.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public int updateByExample(BuffType record, BuffTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("buff_type.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public int updateByPrimaryKeySelective(BuffType record) throws SQLException {
        int rows = sqlMapClient.update("buff_type.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    public int updateByPrimaryKey(BuffType record) throws SQLException {
        int rows = sqlMapClient.update("buff_type.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table buff_type
     *
     * @ibatorgenerated Thu Jan 03 10:58:54 CST 2013
     */
    private static class UpdateByExampleParms extends BuffTypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, BuffTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}