package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.CityTong;
import com.ppsea.ds.data.model.CityTongExample;
import java.sql.SQLException;
import java.util.List;

public class CityTongDAOImpl implements CityTongDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public CityTongDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public int countByExample(CityTongExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"city_tong.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public int deleteByExample(CityTongExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"city_tong.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		CityTong key = new CityTong();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"city_tong.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public void insert(CityTong record) throws SQLException {
		sqlMapClient.insert("city_tong.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public void insertSelective(CityTong record) throws SQLException {
		sqlMapClient
				.insert("city_tong.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<CityTong> selectByExample(CityTongExample example)
			throws SQLException {
		List<CityTong> list = sqlMapClient.queryForList(
				"city_tong.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public CityTong selectByPrimaryKey(Integer id) throws SQLException {
		CityTong key = new CityTong();
		key.setId(id);
		CityTong record = (CityTong) sqlMapClient.queryForObject(
				"city_tong.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public int updateByExampleSelective(CityTong record, CityTongExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"city_tong.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public int updateByExample(CityTong record, CityTongExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"city_tong.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public int updateByPrimaryKeySelective(CityTong record) throws SQLException {
		int rows = sqlMapClient
				.update(
						"city_tong.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	public int updateByPrimaryKey(CityTong record) throws SQLException {
		int rows = sqlMapClient.update(
				"city_tong.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table city_tong
	 * @ibatorgenerated  Wed May 12 14:13:13 CST 2010
	 */
	private static class UpdateByExampleParms extends CityTongExample {
		private Object record;

		public UpdateByExampleParms(Object record, CityTongExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}