package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.CityFacility;
import com.ppsea.ds.data.model.CityFacilityExample;
import java.sql.SQLException;
import java.util.List;

public class CityFacilityDAOImpl implements CityFacilityDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public CityFacilityDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public int countByExample(CityFacilityExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("city_facility.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public int deleteByExample(CityFacilityExample example) throws SQLException {
        int rows = sqlMapClient.delete("city_facility.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        CityFacility key = new CityFacility();
        key.setId(id);
        int rows = sqlMapClient.delete("city_facility.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer insert(CityFacility record) throws SQLException {
        Object newKey = sqlMapClient.insert("city_facility.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer insertSelective(CityFacility record) throws SQLException {
        Object newKey = sqlMapClient.insert("city_facility.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public List selectByExample(CityFacilityExample example) throws SQLException {
        List list = sqlMapClient.queryForList("city_facility.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public CityFacility selectByPrimaryKey(Integer id) throws SQLException {
        CityFacility key = new CityFacility();
        key.setId(id);
        CityFacility record = (CityFacility) sqlMapClient.queryForObject("city_facility.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public int updateByExampleSelective(CityFacility record, CityFacilityExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("city_facility.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public int updateByExample(CityFacility record, CityFacilityExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("city_facility.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public int updateByPrimaryKeySelective(CityFacility record) throws SQLException {
        int rows = sqlMapClient.update("city_facility.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public int updateByPrimaryKey(CityFacility record) throws SQLException {
        int rows = sqlMapClient.update("city_facility.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private static class UpdateByExampleParms extends CityFacilityExample {
        private Object record;

        public UpdateByExampleParms(Object record, CityFacilityExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}