package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.CityFacility;
import com.ppsea.ds.data.model.CityFacilityExample;
import java.sql.SQLException;
import java.util.List;

public interface CityFacilityDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    int countByExample(CityFacilityExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    int deleteByExample(CityFacilityExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    Integer insert(CityFacility record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    Integer insertSelective(CityFacility record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    List selectByExample(CityFacilityExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    CityFacility selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    int updateByExampleSelective(CityFacility record, CityFacilityExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    int updateByExample(CityFacility record, CityFacilityExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    int updateByPrimaryKeySelective(CityFacility record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    int updateByPrimaryKey(CityFacility record) throws SQLException;
}