package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.CityFacilityMonster;
import com.ppsea.ds.data.model.CityFacilityMonsterExample;
import java.sql.SQLException;
import java.util.List;

public class CityFacilityMonsterDAOImpl implements CityFacilityMonsterDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public CityFacilityMonsterDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public int countByExample(CityFacilityMonsterExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("city_facility_monster.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public int deleteByExample(CityFacilityMonsterExample example) throws SQLException {
        int rows = sqlMapClient.delete("city_facility_monster.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        CityFacilityMonster key = new CityFacilityMonster();
        key.setId(id);
        int rows = sqlMapClient.delete("city_facility_monster.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public void insert(CityFacilityMonster record) throws SQLException {
        sqlMapClient.insert("city_facility_monster.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public void insertSelective(CityFacilityMonster record) throws SQLException {
        sqlMapClient.insert("city_facility_monster.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<CityFacilityMonster> selectByExample(CityFacilityMonsterExample example) throws SQLException {
        List<CityFacilityMonster> list = sqlMapClient.queryForList("city_facility_monster.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public CityFacilityMonster selectByPrimaryKey(Integer id) throws SQLException {
        CityFacilityMonster key = new CityFacilityMonster();
        key.setId(id);
        CityFacilityMonster record = (CityFacilityMonster) sqlMapClient.queryForObject("city_facility_monster.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public int updateByExampleSelective(CityFacilityMonster record, CityFacilityMonsterExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("city_facility_monster.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public int updateByExample(CityFacilityMonster record, CityFacilityMonsterExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("city_facility_monster.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public int updateByPrimaryKeySelective(CityFacilityMonster record) throws SQLException {
        int rows = sqlMapClient.update("city_facility_monster.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    public int updateByPrimaryKey(CityFacilityMonster record) throws SQLException {
        int rows = sqlMapClient.update("city_facility_monster.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table city_facility_monster
     *
     * @ibatorgenerated Sat Apr 24 15:33:47 CST 2010
     */
    private static class UpdateByExampleParms extends CityFacilityMonsterExample {
        private Object record;

        public UpdateByExampleParms(Object record, CityFacilityMonsterExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}