package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ppsea.ds.data.model.EventResult;
import com.ppsea.ds.data.model.EventResultExample;

public interface EventResultDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	Integer insert(EventResult record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	int updateByPrimaryKey(EventResult record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	int updateByPrimaryKeySelective(EventResult record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	List<EventResult> selectByExample(EventResultExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	EventResult selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	int deleteByExample(EventResultExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	int countByExample(EventResultExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	int updateByExampleSelective(EventResult record, EventResultExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	int updateByExample(EventResult record, EventResultExample example)
			throws SQLException;
}