package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ppsea.ds.data.model.EventExtraDesc;
import com.ppsea.ds.data.model.EventExtraDescExample;

public interface EventExtraDescDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    Integer insert(EventExtraDesc record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    int updateByPrimaryKey(EventExtraDesc record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    int updateByPrimaryKeySelective(EventExtraDesc record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    List<EventExtraDesc> selectByExample(EventExtraDescExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    EventExtraDesc selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    int deleteByExample(EventExtraDescExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    int countByExample(EventExtraDescExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    int updateByExampleSelective(EventExtraDesc record, EventExtraDescExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra_desc
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    int updateByExample(EventExtraDesc record, EventExtraDescExample example) throws SQLException;
}