package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.EventResultSkill;
import com.ppsea.ds.data.model.EventResultSkillExample;

public class EventResultSkillDAOImpl implements EventResultSkillDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public EventResultSkillDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public Integer insert(EventResultSkill record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"event_result_skill.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public int updateByPrimaryKey(EventResultSkill record) throws SQLException {
		int rows = sqlMapClient
				.update(
						"event_result_skill.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public int updateByPrimaryKeySelective(EventResultSkill record)
			throws SQLException {
		int rows = sqlMapClient
				.update(
						"event_result_skill.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<EventResultSkill> selectByExample(
			EventResultSkillExample example) throws SQLException {
		List<EventResultSkill> list = (List<EventResultSkill>) sqlMapClient
				.queryForList(
						"event_result_skill.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public EventResultSkill selectByPrimaryKey(Integer id) throws SQLException {
		EventResultSkill key = new EventResultSkill();
		key.setId(id);
		EventResultSkill record = (EventResultSkill) sqlMapClient
				.queryForObject(
						"event_result_skill.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public int deleteByExample(EventResultSkillExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"event_result_skill.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		EventResultSkill key = new EventResultSkill();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"event_result_skill.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public int countByExample(EventResultSkillExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"event_result_skill.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public int updateByExampleSelective(EventResultSkill record,
			EventResultSkillExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"event_result_skill.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	public int updateByExample(EventResultSkill record,
			EventResultSkillExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"event_result_skill.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table event_result_skill
	 * @abatorgenerated  Mon Mar 09 21:12:15 CST 2009
	 */
	private static class UpdateByExampleParms extends EventResultSkillExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				EventResultSkillExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}