package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.EventPlayer;
import com.ppsea.ds.data.model.EventPlayerExample;

public class EventPlayerDAOImpl implements EventPlayerDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public EventPlayerDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public Integer insert(EventPlayer record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"event_player.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public int updateByPrimaryKey(EventPlayer record) throws SQLException {
		int rows = sqlMapClient.update(
				"event_player.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public int updateByPrimaryKeySelective(EventPlayer record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"event_player.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<EventPlayer> selectByExample(EventPlayerExample example)
			throws SQLException {
		List<EventPlayer> list = (List<EventPlayer>) sqlMapClient.queryForList(
				"event_player.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public EventPlayer selectByPrimaryKey(Integer id) throws SQLException {
		EventPlayer key = new EventPlayer();
		key.setId(id);
		EventPlayer record = (EventPlayer) sqlMapClient.queryForObject(
				"event_player.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public int deleteByExample(EventPlayerExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"event_player.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		EventPlayer key = new EventPlayer();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"event_player.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public int countByExample(EventPlayerExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"event_player.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public int updateByExampleSelective(EventPlayer record,
			EventPlayerExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"event_player.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	public int updateByExample(EventPlayer record, EventPlayerExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"event_player.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table event_player
	 * @abatorgenerated  Sun Mar 08 15:38:12 CST 2009
	 */
	private static class UpdateByExampleParms extends EventPlayerExample {
		private Object record;

		public UpdateByExampleParms(Object record, EventPlayerExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}