package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.EventExtra;
import com.ppsea.ds.data.model.EventExtraExample;

public class EventExtraDAOImpl implements EventExtraDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public EventExtraDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public Integer insert(EventExtra record) throws SQLException {
        Object newKey = sqlMapClient.insert("event_extra.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public int updateByPrimaryKey(EventExtra record) throws SQLException {
        int rows = sqlMapClient.update("event_extra.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public int updateByPrimaryKeySelective(EventExtra record) throws SQLException {
        int rows = sqlMapClient.update("event_extra.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<EventExtra> selectByExample(EventExtraExample example) throws SQLException {
        List<EventExtra> list = (List<EventExtra>) sqlMapClient.queryForList("event_extra.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public EventExtra selectByPrimaryKey(Integer id) throws SQLException {
        EventExtra key = new EventExtra();
        key.setId(id);
        EventExtra record = (EventExtra) sqlMapClient.queryForObject("event_extra.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public int deleteByExample(EventExtraExample example) throws SQLException {
        int rows = sqlMapClient.delete("event_extra.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        EventExtra key = new EventExtra();
        key.setId(id);
        int rows = sqlMapClient.delete("event_extra.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public int countByExample(EventExtraExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("event_extra.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public int updateByExampleSelective(EventExtra record, EventExtraExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("event_extra.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public int updateByExample(EventExtra record, EventExtraExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("event_extra.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table event_extra
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    private static class UpdateByExampleParms extends EventExtraExample {
        private Object record;

        public UpdateByExampleParms(Object record, EventExtraExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}