package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.EventRoute;
import com.ppsea.ds.data.model.EventRouteExample;

public class EventRouteDAOImpl implements EventRouteDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public EventRouteDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public Integer insert(EventRoute record) throws SQLException {
        Object newKey = sqlMapClient.insert("event_route.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public int updateByPrimaryKey(EventRoute record) throws SQLException {
        int rows = sqlMapClient.update("event_route.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public int updateByPrimaryKeySelective(EventRoute record) throws SQLException {
        int rows = sqlMapClient.update("event_route.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    @SuppressWarnings("unchecked")
    public List<EventRoute> selectByExample(EventRouteExample example) throws SQLException {
        List<EventRoute> list = (List<EventRoute>) sqlMapClient.queryForList("event_route.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public EventRoute selectByPrimaryKey(Integer id) throws SQLException {
        EventRoute key = new EventRoute();
        key.setId(id);
        EventRoute record = (EventRoute) sqlMapClient.queryForObject("event_route.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public int deleteByExample(EventRouteExample example) throws SQLException {
        int rows = sqlMapClient.delete("event_route.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        EventRoute key = new EventRoute();
        key.setId(id);
        int rows = sqlMapClient.delete("event_route.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public int countByExample(EventRouteExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("event_route.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public int updateByExampleSelective(EventRoute record, EventRouteExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("event_route.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    public int updateByExample(EventRoute record, EventRouteExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("event_route.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table event_route
     *
     * @abatorgenerated Sun Mar 08 12:47:33 CST 2009
     */
    private static class UpdateByExampleParms extends EventRouteExample {
        private Object record;

        public UpdateByExampleParms(Object record, EventRouteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}