package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.Facility;
import com.ppsea.ds.data.model.FacilityExample;
import java.sql.SQLException;
import java.util.List;

public class FacilityDAOImpl implements FacilityDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public FacilityDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public int countByExample(FacilityExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"facility.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public int deleteByExample(FacilityExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"facility.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Facility key = new Facility();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"facility.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public Integer insert(Facility record) throws SQLException {
		Object newKey = sqlMapClient.insert("facility.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public Integer insertSelective(Facility record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"facility.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public List selectByExample(FacilityExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"facility.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public Facility selectByPrimaryKey(Integer id) throws SQLException {
		Facility key = new Facility();
		key.setId(id);
		Facility record = (Facility) sqlMapClient.queryForObject(
				"facility.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public int updateByExampleSelective(Facility record, FacilityExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"facility.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public int updateByExample(Facility record, FacilityExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"facility.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public int updateByPrimaryKeySelective(Facility record) throws SQLException {
		int rows = sqlMapClient.update(
				"facility.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	public int updateByPrimaryKey(Facility record) throws SQLException {
		int rows = sqlMapClient.update(
				"facility.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table facility
	 * @ibatorgenerated  Wed May 12 18:09:12 CST 2010
	 */
	private static class UpdateByExampleParms extends FacilityExample {
		private Object record;

		public UpdateByExampleParms(Object record, FacilityExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}