package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.FarmPre;
import com.ppsea.ds.data.model.FarmPreExample;
import java.sql.SQLException;
import java.util.List;

public class FarmPreDAOImpl implements FarmPreDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public FarmPreDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public int countByExample(FarmPreExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("farm_pre.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public int deleteByExample(FarmPreExample example) throws SQLException {
        int rows = sqlMapClient.delete("farm_pre.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        FarmPre key = new FarmPre();
        key.setId(id);
        int rows = sqlMapClient.delete("farm_pre.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public Integer insert(FarmPre record) throws SQLException {
        Object newKey = sqlMapClient.insert("farm_pre.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public Integer insertSelective(FarmPre record) throws SQLException {
        Object newKey = sqlMapClient.insert("farm_pre.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public List selectByExample(FarmPreExample example) throws SQLException {
        List list = sqlMapClient.queryForList("farm_pre.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public FarmPre selectByPrimaryKey(Integer id) throws SQLException {
        FarmPre key = new FarmPre();
        key.setId(id);
        FarmPre record = (FarmPre) sqlMapClient.queryForObject("farm_pre.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public int updateByExampleSelective(FarmPre record, FarmPreExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("farm_pre.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public int updateByExample(FarmPre record, FarmPreExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("farm_pre.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public int updateByPrimaryKeySelective(FarmPre record) throws SQLException {
        int rows = sqlMapClient.update("farm_pre.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    public int updateByPrimaryKey(FarmPre record) throws SQLException {
        int rows = sqlMapClient.update("farm_pre.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table farm_pre
     *
     * @ibatorgenerated Fri Mar 01 13:49:53 CST 2013
     */
    private static class UpdateByExampleParms extends FarmPreExample {
        private Object record;

        public UpdateByExampleParms(Object record, FarmPreExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}