package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.GoodsItem;
import com.ppsea.ds.data.model.GoodsItemExample;
import java.sql.SQLException;
import java.util.List;

public class GoodsItemDAOImpl implements GoodsItemDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public GoodsItemDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public Integer insert(GoodsItem record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"goods_item.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public int updateByPrimaryKey(GoodsItem record) throws SQLException {
		int rows = sqlMapClient.update(
				"goods_item.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public int updateByPrimaryKeySelective(GoodsItem record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"goods_item.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<GoodsItem> selectByExample(GoodsItemExample example)
			throws SQLException {
		List<GoodsItem> list = (List<GoodsItem>) sqlMapClient.queryForList(
				"goods_item.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public GoodsItem selectByPrimaryKey(Integer id) throws SQLException {
		GoodsItem key = new GoodsItem();
		key.setId(id);
		GoodsItem record = (GoodsItem) sqlMapClient.queryForObject(
				"goods_item.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public int deleteByExample(GoodsItemExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"goods_item.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		GoodsItem key = new GoodsItem();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"goods_item.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public int countByExample(GoodsItemExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"goods_item.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public int updateByExampleSelective(GoodsItem record,
			GoodsItemExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"goods_item.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	public int updateByExample(GoodsItem record, GoodsItemExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"goods_item.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table goods_item
	 * @abatorgenerated  Wed Apr 21 10:31:31 CST 2010
	 */
	private static class UpdateByExampleParms extends GoodsItemExample {
		private Object record;

		public UpdateByExampleParms(Object record, GoodsItemExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}