package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.IdGenerator;
import com.ppsea.ds.data.model.IdGeneratorExample;
import java.sql.SQLException;
import java.util.List;

public class IdGeneratorDAOImpl implements IdGeneratorDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public IdGeneratorDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public int countByExample(IdGeneratorExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("id_generator.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public int deleteByExample(IdGeneratorExample example) throws SQLException {
        int rows = sqlMapClient.delete("id_generator.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        IdGenerator key = new IdGenerator();
        key.setId(id);
        int rows = sqlMapClient.delete("id_generator.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public Integer insert(IdGenerator record) throws SQLException {
        Object newKey = sqlMapClient.insert("id_generator.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public Integer insertSelective(IdGenerator record) throws SQLException {
        Object newKey = sqlMapClient.insert("id_generator.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public List selectByExample(IdGeneratorExample example) throws SQLException {
        List list = sqlMapClient.queryForList("id_generator.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public IdGenerator selectByPrimaryKey(Integer id) throws SQLException {
        IdGenerator key = new IdGenerator();
        key.setId(id);
        IdGenerator record = (IdGenerator) sqlMapClient.queryForObject("id_generator.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public int updateByExampleSelective(IdGenerator record, IdGeneratorExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("id_generator.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public int updateByExample(IdGenerator record, IdGeneratorExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("id_generator.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public int updateByPrimaryKeySelective(IdGenerator record) throws SQLException {
        int rows = sqlMapClient.update("id_generator.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    public int updateByPrimaryKey(IdGenerator record) throws SQLException {
        int rows = sqlMapClient.update("id_generator.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table id_generator
     *
     * @ibatorgenerated Mon Mar 29 19:21:26 CST 2010
     */
    private static class UpdateByExampleParms extends IdGeneratorExample {
        private Object record;

        public UpdateByExampleParms(Object record, IdGeneratorExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}