package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.IntimateScoreRank;
import com.ppsea.ds.data.model.IntimateScoreRankExample;
import java.sql.SQLException;
import java.util.List;

public class IntimateScoreRankDAOImpl implements IntimateScoreRankDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public IntimateScoreRankDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public int countByExample(IntimateScoreRankExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"intimate_score_rank.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public int deleteByExample(IntimateScoreRankExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"intimate_score_rank.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		IntimateScoreRank key = new IntimateScoreRank();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"intimate_score_rank.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public Integer insert(IntimateScoreRank record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"intimate_score_rank.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public Integer insertSelective(IntimateScoreRank record)
			throws SQLException {
		Object newKey = sqlMapClient.insert(
				"intimate_score_rank.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public List selectByExample(IntimateScoreRankExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"intimate_score_rank.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public IntimateScoreRank selectByPrimaryKey(Integer id) throws SQLException {
		IntimateScoreRank key = new IntimateScoreRank();
		key.setId(id);
		IntimateScoreRank record = (IntimateScoreRank) sqlMapClient
				.queryForObject(
						"intimate_score_rank.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public int updateByExampleSelective(IntimateScoreRank record,
			IntimateScoreRankExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"intimate_score_rank.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public int updateByExample(IntimateScoreRank record,
			IntimateScoreRankExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"intimate_score_rank.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public int updateByPrimaryKeySelective(IntimateScoreRank record)
			throws SQLException {
		int rows = sqlMapClient
				.update(
						"intimate_score_rank.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	public int updateByPrimaryKey(IntimateScoreRank record) throws SQLException {
		int rows = sqlMapClient.update(
				"intimate_score_rank.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table intimate_score_rank
	 * @ibatorgenerated  Tue Aug 10 20:50:27 CST 2010
	 */
	private static class UpdateByExampleParms extends IntimateScoreRankExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				IntimateScoreRankExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}