package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.ItemDecompose;
import com.ppsea.ds.data.model.ItemDecomposeExample;
import java.sql.SQLException;
import java.util.List;

public class ItemDecomposeDAOImpl implements ItemDecomposeDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public ItemDecomposeDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public int countByExample(ItemDecomposeExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"item_decompose.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public int deleteByExample(ItemDecomposeExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"item_decompose.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		ItemDecompose key = new ItemDecompose();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"item_decompose.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer insert(ItemDecompose record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"item_decompose.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer insertSelective(ItemDecompose record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"item_decompose.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public List selectByExample(ItemDecomposeExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"item_decompose.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public ItemDecompose selectByPrimaryKey(Integer id) throws SQLException {
		ItemDecompose key = new ItemDecompose();
		key.setId(id);
		ItemDecompose record = (ItemDecompose) sqlMapClient.queryForObject(
				"item_decompose.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public int updateByExampleSelective(ItemDecompose record,
			ItemDecomposeExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"item_decompose.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public int updateByExample(ItemDecompose record,
			ItemDecomposeExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"item_decompose.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public int updateByPrimaryKeySelective(ItemDecompose record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"item_decompose.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public int updateByPrimaryKey(ItemDecompose record) throws SQLException {
		int rows = sqlMapClient.update(
				"item_decompose.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table item_decompose
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private static class UpdateByExampleParms extends ItemDecomposeExample {
		private Object record;

		public UpdateByExampleParms(Object record, ItemDecomposeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}