package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.ItemSuitProperty;
import com.ppsea.ds.data.model.ItemSuitPropertyExample;
import java.sql.SQLException;
import java.util.List;

public interface ItemSuitPropertyDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    int countByExample(ItemSuitPropertyExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    int deleteByExample(ItemSuitPropertyExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    Integer insert(ItemSuitProperty record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    Integer insertSelective(ItemSuitProperty record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    List selectByExample(ItemSuitPropertyExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    ItemSuitProperty selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    int updateByExampleSelective(ItemSuitProperty record, ItemSuitPropertyExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    int updateByExample(ItemSuitProperty record, ItemSuitPropertyExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    int updateByPrimaryKeySelective(ItemSuitProperty record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    int updateByPrimaryKey(ItemSuitProperty record) throws SQLException;
}