package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.ItemBetterProty;
import com.ppsea.ds.data.model.ItemBetterProtyExample;
import java.sql.SQLException;
import java.util.List;

public interface ItemBetterProtyDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	int countByExample(ItemBetterProtyExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	int deleteByExample(ItemBetterProtyExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	Integer insert(ItemBetterProty record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	Integer insertSelective(ItemBetterProty record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	List selectByExample(ItemBetterProtyExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	ItemBetterProty selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	int updateByExampleSelective(ItemBetterProty record,
			ItemBetterProtyExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	int updateByExample(ItemBetterProty record, ItemBetterProtyExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	int updateByPrimaryKeySelective(ItemBetterProty record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_better_proty
	 * @ibatorgenerated  Thu Jul 08 11:27:42 CST 2010
	 */
	int updateByPrimaryKey(ItemBetterProty record) throws SQLException;
}