package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.ItemProperty;
import com.ppsea.ds.data.model.ItemPropertyExample;
import java.sql.SQLException;
import java.util.List;

public class ItemPropertyDAOImpl implements ItemPropertyDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:51 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:51 CST 2010
	 */
	public ItemPropertyDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:51 CST 2010
	 */
	public int countByExample(ItemPropertyExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"item_property.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:51 CST 2010
	 */
	public int deleteByExample(ItemPropertyExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"item_property.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:51 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		ItemProperty key = new ItemProperty();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"item_property.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public Integer insert(ItemProperty record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"item_property.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public Integer insertSelective(ItemProperty record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"item_property.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public List selectByExample(ItemPropertyExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"item_property.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public ItemProperty selectByPrimaryKey(Integer id) throws SQLException {
		ItemProperty key = new ItemProperty();
		key.setId(id);
		ItemProperty record = (ItemProperty) sqlMapClient.queryForObject(
				"item_property.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public int updateByExampleSelective(ItemProperty record,
			ItemPropertyExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update(
						"item_property.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public int updateByExample(ItemProperty record, ItemPropertyExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"item_property.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public int updateByPrimaryKeySelective(ItemProperty record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"item_property.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	public int updateByPrimaryKey(ItemProperty record) throws SQLException {
		int rows = sqlMapClient.update(
				"item_property.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table item_property
	 * @ibatorgenerated  Mon May 17 11:07:52 CST 2010
	 */
	private static class UpdateByExampleParms extends ItemPropertyExample {
		private Object record;

		public UpdateByExampleParms(Object record, ItemPropertyExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}