package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.ItemType;
import com.ppsea.ds.data.model.ItemTypeExample;
import java.sql.SQLException;
import java.util.List;

public class ItemTypeDAOImpl implements ItemTypeDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public ItemTypeDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public int countByExample(ItemTypeExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("item_type.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public int deleteByExample(ItemTypeExample example) throws SQLException {
        int rows = sqlMapClient.delete("item_type.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        ItemType key = new ItemType();
        key.setId(id);
        int rows = sqlMapClient.delete("item_type.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public Integer insert(ItemType record) throws SQLException {
        Object newKey = sqlMapClient.insert("item_type.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public Integer insertSelective(ItemType record) throws SQLException {
        Object newKey = sqlMapClient.insert("item_type.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public List selectByExample(ItemTypeExample example) throws SQLException {
        List list = sqlMapClient.queryForList("item_type.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public ItemType selectByPrimaryKey(Integer id) throws SQLException {
        ItemType key = new ItemType();
        key.setId(id);
        ItemType record = (ItemType) sqlMapClient.queryForObject("item_type.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public int updateByExampleSelective(ItemType record, ItemTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("item_type.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public int updateByExample(ItemType record, ItemTypeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("item_type.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public int updateByPrimaryKeySelective(ItemType record) throws SQLException {
        int rows = sqlMapClient.update("item_type.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    public int updateByPrimaryKey(ItemType record) throws SQLException {
        int rows = sqlMapClient.update("item_type.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table item_type
     *
     * @ibatorgenerated Thu Dec 27 22:16:57 CST 2012
     */
    private static class UpdateByExampleParms extends ItemTypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, ItemTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}