package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.ItemSuitProperty;
import com.ppsea.ds.data.model.ItemSuitPropertyExample;
import java.sql.SQLException;
import java.util.List;

public class ItemSuitPropertyDAOImpl implements ItemSuitPropertyDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public ItemSuitPropertyDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public int countByExample(ItemSuitPropertyExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("item_suit_property.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public int deleteByExample(ItemSuitPropertyExample example) throws SQLException {
        int rows = sqlMapClient.delete("item_suit_property.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        ItemSuitProperty key = new ItemSuitProperty();
        key.setId(id);
        int rows = sqlMapClient.delete("item_suit_property.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public Integer insert(ItemSuitProperty record) throws SQLException {
        Object newKey = sqlMapClient.insert("item_suit_property.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public Integer insertSelective(ItemSuitProperty record) throws SQLException {
        Object newKey = sqlMapClient.insert("item_suit_property.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public List selectByExample(ItemSuitPropertyExample example) throws SQLException {
        List list = sqlMapClient.queryForList("item_suit_property.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public ItemSuitProperty selectByPrimaryKey(Integer id) throws SQLException {
        ItemSuitProperty key = new ItemSuitProperty();
        key.setId(id);
        ItemSuitProperty record = (ItemSuitProperty) sqlMapClient.queryForObject("item_suit_property.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public int updateByExampleSelective(ItemSuitProperty record, ItemSuitPropertyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("item_suit_property.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public int updateByExample(ItemSuitProperty record, ItemSuitPropertyExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("item_suit_property.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public int updateByPrimaryKeySelective(ItemSuitProperty record) throws SQLException {
        int rows = sqlMapClient.update("item_suit_property.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    public int updateByPrimaryKey(ItemSuitProperty record) throws SQLException {
        int rows = sqlMapClient.update("item_suit_property.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table item_suit_property
     *
     * @ibatorgenerated Fri Jun 25 13:31:50 CST 2010
     */
    private static class UpdateByExampleParms extends ItemSuitPropertyExample {
        private Object record;

        public UpdateByExampleParms(Object record, ItemSuitPropertyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}