package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.ItemGroup;
import com.ppsea.ds.data.model.ItemGroupExample;
import java.sql.SQLException;
import java.util.List;

public interface ItemGroupDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    int countByExample(ItemGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    int deleteByExample(ItemGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    Integer insert(ItemGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    Integer insertSelective(ItemGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    List selectByExample(ItemGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    ItemGroup selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    int updateByExampleSelective(ItemGroup record, ItemGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    int updateByExample(ItemGroup record, ItemGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    int updateByPrimaryKeySelective(ItemGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table item_group
     *
     * @ibatorgenerated Sat May 15 14:53:24 CST 2010
     */
    int updateByPrimaryKey(ItemGroup record) throws SQLException;
}