package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.ItemIdentify;
import com.ppsea.ds.data.model.ItemIdentifyExample;
import java.sql.SQLException;
import java.util.List;

public class ItemIdentifyDAOImpl implements ItemIdentifyDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public ItemIdentifyDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public int countByExample(ItemIdentifyExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"item_identify.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public int deleteByExample(ItemIdentifyExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"item_identify.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		ItemIdentify key = new ItemIdentify();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"item_identify.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public Integer insert(ItemIdentify record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"item_identify.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public Integer insertSelective(ItemIdentify record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"item_identify.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public List selectByExample(ItemIdentifyExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"item_identify.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public ItemIdentify selectByPrimaryKey(Integer id) throws SQLException {
		ItemIdentify key = new ItemIdentify();
		key.setId(id);
		ItemIdentify record = (ItemIdentify) sqlMapClient.queryForObject(
				"item_identify.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public int updateByExampleSelective(ItemIdentify record,
			ItemIdentifyExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update(
						"item_identify.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public int updateByExample(ItemIdentify record, ItemIdentifyExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"item_identify.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public int updateByPrimaryKeySelective(ItemIdentify record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"item_identify.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	public int updateByPrimaryKey(ItemIdentify record) throws SQLException {
		int rows = sqlMapClient.update(
				"item_identify.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table item_identify
	 * @ibatorgenerated  Thu Aug 19 12:17:17 CST 2010
	 */
	private static class UpdateByExampleParms extends ItemIdentifyExample {
		private Object record;

		public UpdateByExampleParms(Object record, ItemIdentifyExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}