package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.Message;
import com.ppsea.ds.data.model.MessageExample;
import java.sql.SQLException;
import java.util.List;

public class MessageDAOImpl implements MessageDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public MessageDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public int countByExample(MessageExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("message.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public int deleteByExample(MessageExample example) throws SQLException {
        int rows = sqlMapClient.delete("message.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        Message key = new Message();
        key.setId(id);
        int rows = sqlMapClient.delete("message.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public Integer insert(Message record) throws SQLException {
        Object newKey = sqlMapClient.insert("message.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public Integer insertSelective(Message record) throws SQLException {
        Object newKey = sqlMapClient.insert("message.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Message> selectByExample(MessageExample example) throws SQLException {
        List<Message> list = sqlMapClient.queryForList("message.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public Message selectByPrimaryKey(Integer id) throws SQLException {
        Message key = new Message();
        key.setId(id);
        Message record = (Message) sqlMapClient.queryForObject("message.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public int updateByExampleSelective(Message record, MessageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("message.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public int updateByExample(Message record, MessageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("message.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public int updateByPrimaryKeySelective(Message record) throws SQLException {
        int rows = sqlMapClient.update("message.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    public int updateByPrimaryKey(Message record) throws SQLException {
        int rows = sqlMapClient.update("message.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table message
     *
     * @ibatorgenerated Sun May 09 22:49:12 CST 2010
     */
    private static class UpdateByExampleParms extends MessageExample {
        private Object record;

        public UpdateByExampleParms(Object record, MessageExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}