package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ppsea.ds.data.model.MissionPre;
import com.ppsea.ds.data.model.MissionPreExample;

public interface MissionPreDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    Integer insert(MissionPre record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    int updateByPrimaryKey(MissionPre record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    int updateByPrimaryKeySelective(MissionPre record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    List<MissionPre> selectByExample(MissionPreExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    MissionPre selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    int deleteByExample(MissionPreExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    int countByExample(MissionPreExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    int updateByExampleSelective(MissionPre record, MissionPreExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table mission_pre
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    int updateByExample(MissionPre record, MissionPreExample example) throws SQLException;
}