package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.MissionCondition;
import com.ppsea.ds.data.model.MissionConditionExample;
import java.sql.SQLException;
import java.util.List;

public interface MissionConditionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    int countByExample(MissionConditionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    int deleteByExample(MissionConditionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    Integer insert(MissionCondition record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    Integer insertSelective(MissionCondition record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    List selectByExample(MissionConditionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    MissionCondition selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    int updateByExampleSelective(MissionCondition record, MissionConditionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    int updateByExample(MissionCondition record, MissionConditionExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    int updateByPrimaryKeySelective(MissionCondition record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    int updateByPrimaryKey(MissionCondition record) throws SQLException;
}