package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.MissionCondition;
import com.ppsea.ds.data.model.MissionConditionExample;
import java.sql.SQLException;
import java.util.List;

public class MissionConditionDAOImpl implements MissionConditionDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public MissionConditionDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public int countByExample(MissionConditionExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("mission_condition.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public int deleteByExample(MissionConditionExample example) throws SQLException {
        int rows = sqlMapClient.delete("mission_condition.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        MissionCondition key = new MissionCondition();
        key.setId(id);
        int rows = sqlMapClient.delete("mission_condition.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public Integer insert(MissionCondition record) throws SQLException {
        Object newKey = sqlMapClient.insert("mission_condition.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public Integer insertSelective(MissionCondition record) throws SQLException {
        Object newKey = sqlMapClient.insert("mission_condition.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public List selectByExample(MissionConditionExample example) throws SQLException {
        List list = sqlMapClient.queryForList("mission_condition.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public MissionCondition selectByPrimaryKey(Integer id) throws SQLException {
        MissionCondition key = new MissionCondition();
        key.setId(id);
        MissionCondition record = (MissionCondition) sqlMapClient.queryForObject("mission_condition.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public int updateByExampleSelective(MissionCondition record, MissionConditionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("mission_condition.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public int updateByExample(MissionCondition record, MissionConditionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("mission_condition.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public int updateByPrimaryKeySelective(MissionCondition record) throws SQLException {
        int rows = sqlMapClient.update("mission_condition.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    public int updateByPrimaryKey(MissionCondition record) throws SQLException {
        int rows = sqlMapClient.update("mission_condition.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table mission_condition
     *
     * @ibatorgenerated Mon May 31 09:42:06 CST 2010
     */
    private static class UpdateByExampleParms extends MissionConditionExample {
        private Object record;

        public UpdateByExampleParms(Object record, MissionConditionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}