package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.MonsterType;
import com.ppsea.ds.data.model.MonsterTypeExample;
import java.sql.SQLException;
import java.util.List;
import com.ppsea.ds.data.model.MonsterTypeKey;

public class MonsterTypeDAOImpl implements MonsterTypeDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public MonsterTypeDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public int countByExample(MonsterTypeExample example) throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "monster_type.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public int deleteByExample(MonsterTypeExample example) throws SQLException {
	    int rows = sqlMapClient.delete(
	            "monster_type.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    MonsterType key = new MonsterType();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "monster_type.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public Integer insert(MonsterType record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "monster_type.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public Integer insertSelective(MonsterType record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "monster_type.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public List selectByExample(MonsterTypeExample example) throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "monster_type.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public MonsterType selectByPrimaryKey(Integer id) throws SQLException {
	    MonsterType key = new MonsterType();
	    key.setId(id);
	    MonsterType record = (MonsterType) sqlMapClient.queryForObject(
	            "monster_type.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public int updateByExampleSelective(MonsterType record,
            MonsterTypeExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "monster_type.ibatorgenerated_updateByExampleSelective", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public int updateByExample(MonsterType record, MonsterTypeExample example)
            throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "monster_type.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public int updateByPrimaryKeySelective(MonsterType record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "monster_type.ibatorgenerated_updateByPrimaryKeySelective",
	            record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    public int updateByPrimaryKey(MonsterType record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "monster_type.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table monster_type
     * @ibatorgenerated  Tue Sep 14 13:36:59 CST 2010
     */
    private static class UpdateByExampleParms extends MonsterTypeExample {
	    private Object record;

	    public UpdateByExampleParms(Object record, MonsterTypeExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}