package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.Notice;
import com.ppsea.ds.data.model.NoticeExample;
import java.sql.SQLException;
import java.util.List;

public interface NoticeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int countByExample(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int deleteByExample(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	Integer insert(Notice record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	Integer insertSelective(Notice record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	List selectByExampleWithBLOBs(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	List selectByExampleWithoutBLOBs(NoticeExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	Notice selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int updateByExampleSelective(Notice record, NoticeExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int updateByExampleWithBLOBs(Notice record, NoticeExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int updateByExampleWithoutBLOBs(Notice record, NoticeExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int updateByPrimaryKeySelective(Notice record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int updateByPrimaryKeyWithBLOBs(Notice record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table notice
	 * @ibatorgenerated  Thu Apr 29 10:16:36 CST 2010
	 */
	int updateByPrimaryKeyWithoutBLOBs(Notice record) throws SQLException;
	
	List<Notice> selectNotice() throws SQLException;
}