package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ppsea.ds.data.model.NpcInteraction;
import com.ppsea.ds.data.model.NpcInteractionExample;

public interface NpcInteractionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	int countByExample(NpcInteractionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	int deleteByExample(NpcInteractionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	Integer insert(NpcInteraction record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	Integer insertSelective(NpcInteraction record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	List selectByExample(NpcInteractionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	NpcInteraction selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	int updateByExampleSelective(NpcInteraction record,
			NpcInteractionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	int updateByExample(NpcInteraction record, NpcInteractionExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	int updateByPrimaryKeySelective(NpcInteraction record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	int updateByPrimaryKey(NpcInteraction record) throws SQLException;
}