package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.NpcInteraction;
import com.ppsea.ds.data.model.NpcInteractionExample;

public class NpcInteractionDAOImpl implements NpcInteractionDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public NpcInteractionDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public int countByExample(NpcInteractionExample example)
			throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"npc_interaction.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public int deleteByExample(NpcInteractionExample example)
			throws SQLException {
		int rows = sqlMapClient.delete(
				"npc_interaction.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		NpcInteraction key = new NpcInteraction();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"npc_interaction.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public Integer insert(NpcInteraction record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"npc_interaction.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public Integer insertSelective(NpcInteraction record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"npc_interaction.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public List selectByExample(NpcInteractionExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"npc_interaction.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public NpcInteraction selectByPrimaryKey(Integer id) throws SQLException {
		NpcInteraction key = new NpcInteraction();
		key.setId(id);
		NpcInteraction record = (NpcInteraction) sqlMapClient.queryForObject(
				"npc_interaction.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public int updateByExampleSelective(NpcInteraction record,
			NpcInteractionExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"npc_interaction.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public int updateByExample(NpcInteraction record,
			NpcInteractionExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"npc_interaction.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public int updateByPrimaryKeySelective(NpcInteraction record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"npc_interaction.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	public int updateByPrimaryKey(NpcInteraction record) throws SQLException {
		int rows = sqlMapClient.update(
				"npc_interaction.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table npc_interaction
	 * @ibatorgenerated  Mon Dec 31 10:23:22 CST 2012
	 */
	private static class UpdateByExampleParms extends NpcInteractionExample {
		private Object record;

		public UpdateByExampleParms(Object record, NpcInteractionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}