package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.NpcMission;
import com.ppsea.ds.data.model.NpcMissionExample;

public class NpcMissionDAOImpl implements NpcMissionDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public NpcMissionDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public Integer insert(NpcMission record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"npc_mission.abatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public int updateByPrimaryKey(NpcMission record) throws SQLException {
		int rows = sqlMapClient.update(
				"npc_mission.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public int updateByPrimaryKeySelective(NpcMission record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"npc_mission.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<NpcMission> selectByExample(NpcMissionExample example)
			throws SQLException {
		List<NpcMission> list = (List<NpcMission>) sqlMapClient.queryForList(
				"npc_mission.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public NpcMission selectByPrimaryKey(Integer id) throws SQLException {
		NpcMission key = new NpcMission();
		key.setId(id);
		NpcMission record = (NpcMission) sqlMapClient.queryForObject(
				"npc_mission.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public int deleteByExample(NpcMissionExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"npc_mission.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		NpcMission key = new NpcMission();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"npc_mission.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public int countByExample(NpcMissionExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"npc_mission.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public int updateByExampleSelective(NpcMission record,
			NpcMissionExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"npc_mission.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	public int updateByExample(NpcMission record, NpcMissionExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"npc_mission.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table npc_mission
	 * @abatorgenerated  Wed Jan 21 10:46:13 CST 2009
	 */
	private static class UpdateByExampleParms extends NpcMissionExample {
		private Object record;

		public UpdateByExampleParms(Object record, NpcMissionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}