package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.PetLevel;
import com.ppsea.ds.data.model.PetLevelExample;
import java.sql.SQLException;
import java.util.List;

public interface PetLevelDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	int countByExample(PetLevelExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	int deleteByExample(PetLevelExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	Integer insert(PetLevel record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	Integer insertSelective(PetLevel record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	List selectByExample(PetLevelExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	PetLevel selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	int updateByExampleSelective(PetLevel record, PetLevelExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	int updateByExample(PetLevel record, PetLevelExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	int updateByPrimaryKeySelective(PetLevel record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table pet_level
	 * @ibatorgenerated  Mon Apr 26 14:31:49 CST 2010
	 */
	int updateByPrimaryKey(PetLevel record) throws SQLException;
}