package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerActiveRewards;
import com.ppsea.ds.data.model.PlayerActiveRewardsExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerActiveRewardsDAOImpl implements PlayerActiveRewardsDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public PlayerActiveRewardsDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public int countByExample(PlayerActiveRewardsExample example)
            throws SQLException {
	    Integer count = (Integer) sqlMapClient
	            .queryForObject(
	                    "player_active_rewards.ibatorgenerated_countByExample",
	                    example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public int deleteByExample(PlayerActiveRewardsExample example)
            throws SQLException {
	    int rows = sqlMapClient.delete(
	            "player_active_rewards.ibatorgenerated_deleteByExample",
	            example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
	    PlayerActiveRewards key = new PlayerActiveRewards();
	    key.setId(id);
	    int rows = sqlMapClient
	            .delete(
	                    "player_active_rewards.ibatorgenerated_deleteByPrimaryKey",
	                    key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public Long insert(PlayerActiveRewards record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_active_rewards.ibatorgenerated_insert", record);
	    return (Long) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public Long insertSelective(PlayerActiveRewards record) throws SQLException {
	    Object newKey = sqlMapClient
	            .insert(
	                    "player_active_rewards.ibatorgenerated_insertSelective",
	                    record);
	    return (Long) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public List selectByExample(PlayerActiveRewardsExample example)
            throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "player_active_rewards.ibatorgenerated_selectByExample",
	            example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public PlayerActiveRewards selectByPrimaryKey(Long id) throws SQLException {
	    PlayerActiveRewards key = new PlayerActiveRewards();
	    key.setId(id);
	    PlayerActiveRewards record = (PlayerActiveRewards) sqlMapClient
	            .queryForObject(
	                    "player_active_rewards.ibatorgenerated_selectByPrimaryKey",
	                    key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public int updateByExampleSelective(PlayerActiveRewards record,
            PlayerActiveRewardsExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient
	            .update(
	                    "player_active_rewards.ibatorgenerated_updateByExampleSelective",
	                    parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public int updateByExample(PlayerActiveRewards record,
            PlayerActiveRewardsExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_active_rewards.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public int updateByPrimaryKeySelective(PlayerActiveRewards record)
            throws SQLException {
	    int rows = sqlMapClient
	            .update(
	                    "player_active_rewards.ibatorgenerated_updateByPrimaryKeySelective",
	                    record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    public int updateByPrimaryKey(PlayerActiveRewards record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_active_rewards.ibatorgenerated_updateByPrimaryKey",
	            record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_active_rewards
     * @ibatorgenerated  Sat Apr 02 10:47:28 CST 2011
     */
    private static class UpdateByExampleParms extends
            PlayerActiveRewardsExample {
	    private Object record;

	    public UpdateByExampleParms(Object record,
	            PlayerActiveRewardsExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}