package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerMission;
import com.ppsea.ds.data.model.PlayerMissionExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerMissionDAOImpl implements PlayerMissionDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public PlayerMissionDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public int countByExample(PlayerMissionExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_mission.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public int deleteByExample(PlayerMissionExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_mission.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerMission key = new PlayerMission();
        key.setId(id);
        int rows = sqlMapClient.delete("player_mission.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public Integer insert(PlayerMission record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_mission.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public Integer insertSelective(PlayerMission record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_mission.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public List selectByExample(PlayerMissionExample example) throws SQLException {
        List list = sqlMapClient.queryForList("player_mission.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public PlayerMission selectByPrimaryKey(Integer id) throws SQLException {
        PlayerMission key = new PlayerMission();
        key.setId(id);
        PlayerMission record = (PlayerMission) sqlMapClient.queryForObject("player_mission.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public int updateByExampleSelective(PlayerMission record, PlayerMissionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_mission.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public int updateByExample(PlayerMission record, PlayerMissionExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_mission.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public int updateByPrimaryKeySelective(PlayerMission record) throws SQLException {
        int rows = sqlMapClient.update("player_mission.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    public int updateByPrimaryKey(PlayerMission record) throws SQLException {
        int rows = sqlMapClient.update("player_mission.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table player_mission
     *
     * @ibatorgenerated Fri May 28 13:21:21 CST 2010
     */
    private static class UpdateByExampleParms extends PlayerMissionExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerMissionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}