package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.PlayerItemUsing;
import com.ppsea.ds.data.model.PlayerItemUsingExample;
import java.sql.SQLException;
import java.util.List;

public interface PlayerItemUsingDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    int countByExample(PlayerItemUsingExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    int deleteByExample(PlayerItemUsingExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    Integer insert(PlayerItemUsing record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    Integer insertSelective(PlayerItemUsing record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    List selectByExample(PlayerItemUsingExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    PlayerItemUsing selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    int updateByExampleSelective(PlayerItemUsing record, PlayerItemUsingExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    int updateByExample(PlayerItemUsing record, PlayerItemUsingExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    int updateByPrimaryKeySelective(PlayerItemUsing record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    int updateByPrimaryKey(PlayerItemUsing record) throws SQLException;
}