package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerName;
import com.ppsea.ds.data.model.PlayerNameExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerNameDAOImpl implements PlayerNameDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public PlayerNameDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public int countByExample(PlayerNameExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_name.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public int deleteByExample(PlayerNameExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_name.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerName key = new PlayerName();
        key.setId(id);
        int rows = sqlMapClient.delete("player_name.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public Integer insert(PlayerName record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_name.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public Integer insertSelective(PlayerName record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_name.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public List selectByExample(PlayerNameExample example) throws SQLException {
        List list = sqlMapClient.queryForList("player_name.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public PlayerName selectByPrimaryKey(Integer id) throws SQLException {
        PlayerName key = new PlayerName();
        key.setId(id);
        PlayerName record = (PlayerName) sqlMapClient.queryForObject("player_name.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public int updateByExampleSelective(PlayerName record, PlayerNameExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_name.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public int updateByExample(PlayerName record, PlayerNameExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_name.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public int updateByPrimaryKeySelective(PlayerName record) throws SQLException {
        int rows = sqlMapClient.update("player_name.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    public int updateByPrimaryKey(PlayerName record) throws SQLException {
        int rows = sqlMapClient.update("player_name.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table player_name
     *
     * @ibatorgenerated Mon Nov 29 13:32:51 CST 2010
     */
    private static class UpdateByExampleParms extends PlayerNameExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerNameExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}