package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerDartPrize;
import com.ppsea.ds.data.model.PlayerDartPrizeExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerDartPrizeDAOImpl implements PlayerDartPrizeDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public PlayerDartPrizeDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public int countByExample(PlayerDartPrizeExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_dart_prize.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public int deleteByExample(PlayerDartPrizeExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_dart_prize.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerDartPrize key = new PlayerDartPrize();
        key.setId(id);
        int rows = sqlMapClient.delete("player_dart_prize.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public Integer insert(PlayerDartPrize record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_dart_prize.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public Integer insertSelective(PlayerDartPrize record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_dart_prize.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public List selectByExample(PlayerDartPrizeExample example) throws SQLException {
        List list = sqlMapClient.queryForList("player_dart_prize.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public PlayerDartPrize selectByPrimaryKey(Integer id) throws SQLException {
        PlayerDartPrize key = new PlayerDartPrize();
        key.setId(id);
        PlayerDartPrize record = (PlayerDartPrize) sqlMapClient.queryForObject("player_dart_prize.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public int updateByExampleSelective(PlayerDartPrize record, PlayerDartPrizeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_dart_prize.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public int updateByExample(PlayerDartPrize record, PlayerDartPrizeExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_dart_prize.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public int updateByPrimaryKeySelective(PlayerDartPrize record) throws SQLException {
        int rows = sqlMapClient.update("player_dart_prize.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    public int updateByPrimaryKey(PlayerDartPrize record) throws SQLException {
        int rows = sqlMapClient.update("player_dart_prize.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table player_dart_prize
     *
     * @ibatorgenerated Fri Feb 15 10:13:05 CST 2013
     */
    private static class UpdateByExampleParms extends PlayerDartPrizeExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerDartPrizeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}