package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerFishing;
import com.ppsea.ds.data.model.PlayerFishingExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerFishingDAOImpl implements PlayerFishingDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public PlayerFishingDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public int countByExample(PlayerFishingExample example) throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "player_fishing.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public int deleteByExample(PlayerFishingExample example)
            throws SQLException {
	    int rows = sqlMapClient.delete(
	            "player_fishing.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    PlayerFishing key = new PlayerFishing();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "player_fishing.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public Integer insert(PlayerFishing record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_fishing.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public Integer insertSelective(PlayerFishing record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_fishing.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public List selectByExample(PlayerFishingExample example)
            throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "player_fishing.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public PlayerFishing selectByPrimaryKey(Integer id) throws SQLException {
	    PlayerFishing key = new PlayerFishing();
	    key.setId(id);
	    PlayerFishing record = (PlayerFishing) sqlMapClient.queryForObject(
	            "player_fishing.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public int updateByExampleSelective(PlayerFishing record,
            PlayerFishingExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_fishing.ibatorgenerated_updateByExampleSelective",
	            parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public int updateByExample(PlayerFishing record,
            PlayerFishingExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_fishing.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public int updateByPrimaryKeySelective(PlayerFishing record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_fishing.ibatorgenerated_updateByPrimaryKeySelective",
	            record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    public int updateByPrimaryKey(PlayerFishing record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_fishing.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_fishing
     * @ibatorgenerated  Tue Nov 09 10:15:38 CST 2010
     */
    private static class UpdateByExampleParms extends PlayerFishingExample {
	    private Object record;

	    public UpdateByExampleParms(Object record, PlayerFishingExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}