package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerItemUsing;
import com.ppsea.ds.data.model.PlayerItemUsingExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerItemUsingDAOImpl implements PlayerItemUsingDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public PlayerItemUsingDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public int countByExample(PlayerItemUsingExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_item_using.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public int deleteByExample(PlayerItemUsingExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_item_using.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerItemUsing key = new PlayerItemUsing();
        key.setId(id);
        int rows = sqlMapClient.delete("player_item_using.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public Integer insert(PlayerItemUsing record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_item_using.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public Integer insertSelective(PlayerItemUsing record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_item_using.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public List selectByExample(PlayerItemUsingExample example) throws SQLException {
        List list = sqlMapClient.queryForList("player_item_using.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public PlayerItemUsing selectByPrimaryKey(Integer id) throws SQLException {
        PlayerItemUsing key = new PlayerItemUsing();
        key.setId(id);
        PlayerItemUsing record = (PlayerItemUsing) sqlMapClient.queryForObject("player_item_using.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public int updateByExampleSelective(PlayerItemUsing record, PlayerItemUsingExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_item_using.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public int updateByExample(PlayerItemUsing record, PlayerItemUsingExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_item_using.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public int updateByPrimaryKeySelective(PlayerItemUsing record) throws SQLException {
        int rows = sqlMapClient.update("player_item_using.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    public int updateByPrimaryKey(PlayerItemUsing record) throws SQLException {
        int rows = sqlMapClient.update("player_item_using.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table player_item_using
     *
     * @ibatorgenerated Tue May 11 10:45:09 CST 2010
     */
    private static class UpdateByExampleParms extends PlayerItemUsingExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerItemUsingExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}