package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerResell;
import com.ppsea.ds.data.model.PlayerResellExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerResellDAOImpl implements PlayerResellDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public PlayerResellDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int countByExample(PlayerResellExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"player_resell.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int deleteByExample(PlayerResellExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"player_resell.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		PlayerResell key = new PlayerResell();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"player_resell.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public Integer insert(PlayerResell record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_resell.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public Integer insertSelective(PlayerResell record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"player_resell.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public List selectByExampleWithBLOBs(PlayerResellExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"player_resell.ibatorgenerated_selectByExampleWithBLOBs",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public List selectByExampleWithoutBLOBs(PlayerResellExample example)
			throws SQLException {
		List list = sqlMapClient.queryForList(
				"player_resell.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public PlayerResell selectByPrimaryKey(Integer id) throws SQLException {
		PlayerResell key = new PlayerResell();
		key.setId(id);
		PlayerResell record = (PlayerResell) sqlMapClient.queryForObject(
				"player_resell.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int updateByExampleSelective(PlayerResell record,
			PlayerResellExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("player_resell.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int updateByExampleWithBLOBs(PlayerResell record,
			PlayerResellExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient
				.update("player_resell.ibatorgenerated_updateByExampleWithBLOBs",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int updateByExampleWithoutBLOBs(PlayerResell record,
			PlayerResellExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"player_resell.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int updateByPrimaryKeySelective(PlayerResell record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"player_resell.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int updateByPrimaryKeyWithBLOBs(PlayerResell record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"player_resell.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	public int updateByPrimaryKeyWithoutBLOBs(PlayerResell record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"player_resell.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_resell
	 * @ibatorgenerated  Sat Feb 02 00:20:34 CST 2013
	 */
	private static class UpdateByExampleParms extends PlayerResellExample {
		private Object record;

		public UpdateByExampleParms(Object record, PlayerResellExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}