package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.PlayerPasswdHistory;
import com.ppsea.ds.data.model.PlayerPasswdHistoryExample;
import java.sql.SQLException;
import java.util.List;

public interface PlayerPasswdHistoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	int countByExample(PlayerPasswdHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	int deleteByExample(PlayerPasswdHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	Integer insert(PlayerPasswdHistory record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	Integer insertSelective(PlayerPasswdHistory record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	List selectByExample(PlayerPasswdHistoryExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	PlayerPasswdHistory selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	int updateByExampleSelective(PlayerPasswdHistory record,
			PlayerPasswdHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	int updateByExample(PlayerPasswdHistory record,
			PlayerPasswdHistoryExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	int updateByPrimaryKeySelective(PlayerPasswdHistory record)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_passwd_history
	 * @ibatorgenerated  Mon Jun 07 15:26:45 CST 2010
	 */
	int updateByPrimaryKey(PlayerPasswdHistory record) throws SQLException;
}