package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerStoreRoom;
import com.ppsea.ds.data.model.PlayerStoreRoomExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerStoreRoomDAOImpl implements PlayerStoreRoomDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public PlayerStoreRoomDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public int countByExample(PlayerStoreRoomExample example)
            throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "player_store_room.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public int deleteByExample(PlayerStoreRoomExample example)
            throws SQLException {
	    int rows = sqlMapClient.delete(
	            "player_store_room.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    PlayerStoreRoom key = new PlayerStoreRoom();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "player_store_room.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public Integer insert(PlayerStoreRoom record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_store_room.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public Integer insertSelective(PlayerStoreRoom record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_store_room.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public List selectByExample(PlayerStoreRoomExample example)
            throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "player_store_room.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public PlayerStoreRoom selectByPrimaryKey(Integer id) throws SQLException {
	    PlayerStoreRoom key = new PlayerStoreRoom();
	    key.setId(id);
	    PlayerStoreRoom record = (PlayerStoreRoom) sqlMapClient.queryForObject(
	            "player_store_room.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public int updateByExampleSelective(PlayerStoreRoom record,
            PlayerStoreRoomExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_store_room.ibatorgenerated_updateByExampleSelective",
	            parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public int updateByExample(PlayerStoreRoom record,
            PlayerStoreRoomExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_store_room.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public int updateByPrimaryKeySelective(PlayerStoreRoom record)
            throws SQLException {
	    int rows = sqlMapClient
	            .update(
	                    "player_store_room.ibatorgenerated_updateByPrimaryKeySelective",
	                    record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    public int updateByPrimaryKey(PlayerStoreRoom record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_store_room.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_store_room
     * @ibatorgenerated  Fri Feb 25 12:15:41 CST 2011
     */
    private static class UpdateByExampleParms extends PlayerStoreRoomExample {
	    private Object record;

	    public UpdateByExampleParms(Object record,
	            PlayerStoreRoomExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}