package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerPromote;
import com.ppsea.ds.data.model.PlayerPromoteExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerPromoteDAOImpl implements PlayerPromoteDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public PlayerPromoteDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public int countByExample(PlayerPromoteExample example) throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "player_promote.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public int deleteByExample(PlayerPromoteExample example)
            throws SQLException {
	    int rows = sqlMapClient.delete(
	            "player_promote.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    PlayerPromote key = new PlayerPromote();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "player_promote.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Integer insert(PlayerPromote record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_promote.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Integer insertSelective(PlayerPromote record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_promote.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public List selectByExample(PlayerPromoteExample example)
            throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "player_promote.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public PlayerPromote selectByPrimaryKey(Integer id) throws SQLException {
	    PlayerPromote key = new PlayerPromote();
	    key.setId(id);
	    PlayerPromote record = (PlayerPromote) sqlMapClient.queryForObject(
	            "player_promote.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public int updateByExampleSelective(PlayerPromote record,
            PlayerPromoteExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_promote.ibatorgenerated_updateByExampleSelective",
	            parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public int updateByExample(PlayerPromote record,
            PlayerPromoteExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_promote.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public int updateByPrimaryKeySelective(PlayerPromote record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_promote.ibatorgenerated_updateByPrimaryKeySelective",
	            record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public int updateByPrimaryKey(PlayerPromote record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_promote.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_promote
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private static class UpdateByExampleParms extends PlayerPromoteExample {
	    private Object record;

	    public UpdateByExampleParms(Object record, PlayerPromoteExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}