package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerUpgrade;
import com.ppsea.ds.data.model.PlayerUpgradeExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerUpgradeDAOImpl implements PlayerUpgradeDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public PlayerUpgradeDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public int countByExample(PlayerUpgradeExample example) throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "player_upgrade.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public int deleteByExample(PlayerUpgradeExample example)
            throws SQLException {
	    int rows = sqlMapClient.delete(
	            "player_upgrade.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    PlayerUpgrade key = new PlayerUpgrade();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "player_upgrade.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public Integer insert(PlayerUpgrade record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_upgrade.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public Integer insertSelective(PlayerUpgrade record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "player_upgrade.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public List selectByExample(PlayerUpgradeExample example)
            throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "player_upgrade.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public PlayerUpgrade selectByPrimaryKey(Integer id) throws SQLException {
	    PlayerUpgrade key = new PlayerUpgrade();
	    key.setId(id);
	    PlayerUpgrade record = (PlayerUpgrade) sqlMapClient.queryForObject(
	            "player_upgrade.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public int updateByExampleSelective(PlayerUpgrade record,
            PlayerUpgradeExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_upgrade.ibatorgenerated_updateByExampleSelective",
	            parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public int updateByExample(PlayerUpgrade record,
            PlayerUpgradeExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "player_upgrade.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public int updateByPrimaryKeySelective(PlayerUpgrade record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_upgrade.ibatorgenerated_updateByPrimaryKeySelective",
	            record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    public int updateByPrimaryKey(PlayerUpgrade record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "player_upgrade.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table player_upgrade
     * @ibatorgenerated  Sat Jun 05 14:56:22 CST 2010
     */
    private static class UpdateByExampleParms extends PlayerUpgradeExample {
	    private Object record;

	    public UpdateByExampleParms(Object record, PlayerUpgradeExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}