package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerMissionPast;
import com.ppsea.ds.data.model.PlayerMissionPastExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerMissionPastDAOImpl implements PlayerMissionPastDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public PlayerMissionPastDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int countByExample(PlayerMissionPastExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_mission_past.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int deleteByExample(PlayerMissionPastExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_mission_past.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerMissionPast key = new PlayerMissionPast();
        key.setId(id);
        int rows = sqlMapClient.delete("player_mission_past.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public Integer insert(PlayerMissionPast record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_mission_past.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public Integer insertSelective(PlayerMissionPast record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_mission_past.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<PlayerMissionPast> selectByExampleWithBLOBs(PlayerMissionPastExample example) throws SQLException {
        List<PlayerMissionPast> list = sqlMapClient.queryForList("player_mission_past.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<PlayerMissionPast> selectByExampleWithoutBLOBs(PlayerMissionPastExample example) throws SQLException {
        List<PlayerMissionPast> list = sqlMapClient.queryForList("player_mission_past.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public PlayerMissionPast selectByPrimaryKey(Integer id) throws SQLException {
        PlayerMissionPast key = new PlayerMissionPast();
        key.setId(id);
        PlayerMissionPast record = (PlayerMissionPast) sqlMapClient.queryForObject("player_mission_past.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int updateByExampleSelective(PlayerMissionPast record, PlayerMissionPastExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_mission_past.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int updateByExampleWithBLOBs(PlayerMissionPast record, PlayerMissionPastExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_mission_past.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int updateByExampleWithoutBLOBs(PlayerMissionPast record, PlayerMissionPastExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_mission_past.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int updateByPrimaryKeySelective(PlayerMissionPast record) throws SQLException {
        int rows = sqlMapClient.update("player_mission_past.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(PlayerMissionPast record) throws SQLException {
        int rows = sqlMapClient.update("player_mission_past.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(PlayerMissionPast record) throws SQLException {
        int rows = sqlMapClient.update("player_mission_past.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table player_mission_past
     *
     * @ibatorgenerated Fri Apr 23 14:23:33 CST 2010
     */
    private static class UpdateByExampleParms extends PlayerMissionPastExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerMissionPastExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}