package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PlayerSkill;
import com.ppsea.ds.data.model.PlayerSkillExample;
import java.sql.SQLException;
import java.util.List;

public class PlayerSkillDAOImpl implements PlayerSkillDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public PlayerSkillDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public int countByExample(PlayerSkillExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("player_skill.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public int deleteByExample(PlayerSkillExample example) throws SQLException {
        int rows = sqlMapClient.delete("player_skill.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        PlayerSkill key = new PlayerSkill();
        key.setId(id);
        int rows = sqlMapClient.delete("player_skill.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public Integer insert(PlayerSkill record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_skill.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public Integer insertSelective(PlayerSkill record) throws SQLException {
        Object newKey = sqlMapClient.insert("player_skill.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public List selectByExample(PlayerSkillExample example) throws SQLException {
        List list = sqlMapClient.queryForList("player_skill.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public PlayerSkill selectByPrimaryKey(Integer id) throws SQLException {
        PlayerSkill key = new PlayerSkill();
        key.setId(id);
        PlayerSkill record = (PlayerSkill) sqlMapClient.queryForObject("player_skill.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public int updateByExampleSelective(PlayerSkill record, PlayerSkillExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_skill.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public int updateByExample(PlayerSkill record, PlayerSkillExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("player_skill.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public int updateByPrimaryKeySelective(PlayerSkill record) throws SQLException {
        int rows = sqlMapClient.update("player_skill.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    public int updateByPrimaryKey(PlayerSkill record) throws SQLException {
        int rows = sqlMapClient.update("player_skill.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table player_skill
     *
     * @ibatorgenerated Wed Feb 27 14:44:36 CST 2013
     */
    private static class UpdateByExampleParms extends PlayerSkillExample {
        private Object record;

        public UpdateByExampleParms(Object record, PlayerSkillExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}