package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.PointsItem;
import com.ppsea.ds.data.model.PointsItemExample;
import java.sql.SQLException;
import java.util.List;

public class PointsItemDAOImpl implements PointsItemDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public PointsItemDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public int countByExample(PointsItemExample example) throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "points_item.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public int deleteByExample(PointsItemExample example) throws SQLException {
	    int rows = sqlMapClient.delete(
	            "points_item.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    PointsItem key = new PointsItem();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "points_item.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public Integer insert(PointsItem record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "points_item.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public Integer insertSelective(PointsItem record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "points_item.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public List selectByExample(PointsItemExample example) throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "points_item.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public PointsItem selectByPrimaryKey(Integer id) throws SQLException {
	    PointsItem key = new PointsItem();
	    key.setId(id);
	    PointsItem record = (PointsItem) sqlMapClient.queryForObject(
	            "points_item.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public int updateByExampleSelective(PointsItem record,
            PointsItemExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "points_item.ibatorgenerated_updateByExampleSelective", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public int updateByExample(PointsItem record, PointsItemExample example)
            throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "points_item.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public int updateByPrimaryKeySelective(PointsItem record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "points_item.ibatorgenerated_updateByPrimaryKeySelective",
	            record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    public int updateByPrimaryKey(PointsItem record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "points_item.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table points_item
     * @ibatorgenerated  Tue Dec 14 11:41:37 CST 2010
     */
    private static class UpdateByExampleParms extends PointsItemExample {
	    private Object record;

	    public UpdateByExampleParms(Object record, PointsItemExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}