package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ppsea.ds.data.model.Question;
import com.ppsea.ds.data.model.QuestionExample;

public interface QuestionDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	Integer insert(Question record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	int updateByPrimaryKey(Question record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	int updateByPrimaryKeySelective(Question record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	List<Question> selectByExample(QuestionExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	Question selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	int deleteByExample(QuestionExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	int countByExample(QuestionExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	int updateByExampleSelective(Question record, QuestionExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	int updateByExample(Question record, QuestionExample example)
			throws SQLException;
}