package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.QuestionType;
import com.ppsea.ds.data.model.QuestionTypeExample;
import java.sql.SQLException;
import java.util.List;

public interface QuestionTypeDAO {

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    int countByExample(QuestionTypeExample example) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    int deleteByExample(QuestionTypeExample example) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    Integer insert(QuestionType record) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    Integer insertSelective(QuestionType record) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    List selectByExample(QuestionTypeExample example) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    QuestionType selectByPrimaryKey(Integer id) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    int updateByExampleSelective(QuestionType record,
            QuestionTypeExample example) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    int updateByExample(QuestionType record, QuestionTypeExample example)
            throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    int updateByPrimaryKeySelective(QuestionType record) throws SQLException;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table question_type
     * @ibatorgenerated  Wed May 25 16:18:24 CST 2011
     */
    int updateByPrimaryKey(QuestionType record) throws SQLException;
}