package com.ppsea.ds.data.dao;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.Question;
import com.ppsea.ds.data.model.QuestionExample;

public class QuestionDAOImpl implements QuestionDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public QuestionDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public Integer insert(Question record) throws SQLException {
		Object newKey = sqlMapClient.insert("question.abatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public int updateByPrimaryKey(Question record) throws SQLException {
		int rows = sqlMapClient.update(
				"question.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public int updateByPrimaryKeySelective(Question record) throws SQLException {
		int rows = sqlMapClient.update(
				"question.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	@SuppressWarnings("unchecked")
	public List<Question> selectByExample(QuestionExample example)
			throws SQLException {
		List<Question> list = (List<Question>) sqlMapClient.queryForList(
				"question.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public Question selectByPrimaryKey(Integer id) throws SQLException {
		Question key = new Question();
		key.setId(id);
		Question record = (Question) sqlMapClient.queryForObject(
				"question.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public int deleteByExample(QuestionExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"question.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Question key = new Question();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"question.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public int countByExample(QuestionExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"question.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public int updateByExampleSelective(Question record, QuestionExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"question.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	public int updateByExample(Question record, QuestionExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"question.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table question
	 * @abatorgenerated  Mon Feb 09 14:55:46 CST 2009
	 */
	private static class UpdateByExampleParms extends QuestionExample {
		private Object record;

		public UpdateByExampleParms(Object record, QuestionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}