package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.RawMission;
import com.ppsea.ds.data.model.RawMissionExample;
import java.sql.SQLException;
import java.util.List;

public class RawMissionDAOImpl implements RawMissionDAO {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    private SqlMapClient sqlMapClient;

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public RawMissionDAOImpl(SqlMapClient sqlMapClient) {
	    super();
	    this.sqlMapClient = sqlMapClient;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public int countByExample(RawMissionExample example) throws SQLException {
	    Integer count = (Integer) sqlMapClient.queryForObject(
	            "raw_mission.ibatorgenerated_countByExample", example);
	    return count.intValue();
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public int deleteByExample(RawMissionExample example) throws SQLException {
	    int rows = sqlMapClient.delete(
	            "raw_mission.ibatorgenerated_deleteByExample", example);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
	    RawMission key = new RawMission();
	    key.setId(id);
	    int rows = sqlMapClient.delete(
	            "raw_mission.ibatorgenerated_deleteByPrimaryKey", key);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public Integer insert(RawMission record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "raw_mission.ibatorgenerated_insert", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public Integer insertSelective(RawMission record) throws SQLException {
	    Object newKey = sqlMapClient.insert(
	            "raw_mission.ibatorgenerated_insertSelective", record);
	    return (Integer) newKey;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public List selectByExample(RawMissionExample example) throws SQLException {
	    List list = sqlMapClient.queryForList(
	            "raw_mission.ibatorgenerated_selectByExample", example);
	    return list;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public RawMission selectByPrimaryKey(Integer id) throws SQLException {
	    RawMission key = new RawMission();
	    key.setId(id);
	    RawMission record = (RawMission) sqlMapClient.queryForObject(
	            "raw_mission.ibatorgenerated_selectByPrimaryKey", key);
	    return record;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public int updateByExampleSelective(RawMission record,
            RawMissionExample example) throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "raw_mission.ibatorgenerated_updateByExampleSelective", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public int updateByExample(RawMission record, RawMissionExample example)
            throws SQLException {
	    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
	    int rows = sqlMapClient.update(
	            "raw_mission.ibatorgenerated_updateByExample", parms);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public int updateByPrimaryKeySelective(RawMission record)
            throws SQLException {
	    int rows = sqlMapClient.update(
	            "raw_mission.ibatorgenerated_updateByPrimaryKeySelective",
	            record);
	    return rows;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    public int updateByPrimaryKey(RawMission record) throws SQLException {
	    int rows = sqlMapClient.update(
	            "raw_mission.ibatorgenerated_updateByPrimaryKey", record);
	    return rows;
    }

	/**
     * This class was generated by Apache iBATIS ibator. This class corresponds to the database table raw_mission
     * @ibatorgenerated  Wed Jan 19 14:22:45 CST 2011
     */
    private static class UpdateByExampleParms extends RawMissionExample {
	    private Object record;

	    public UpdateByExampleParms(Object record, RawMissionExample example) {
		    super(example);
		    this.record = record;
	    }

	    public Object getRecord() {
		    return record;
	    }
    }
}