package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.ResellPrice;
import com.ppsea.ds.data.model.ResellPriceExample;
import java.sql.SQLException;
import java.util.List;

public class ResellPriceDAOImpl implements ResellPriceDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public ResellPriceDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public int countByExample(ResellPriceExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"resell_price.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public int deleteByExample(ResellPriceExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"resell_price.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		ResellPrice key = new ResellPrice();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"resell_price.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public Integer insert(ResellPrice record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"resell_price.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public Integer insertSelective(ResellPrice record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"resell_price.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public List selectByExample(ResellPriceExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"resell_price.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public ResellPrice selectByPrimaryKey(Integer id) throws SQLException {
		ResellPrice key = new ResellPrice();
		key.setId(id);
		ResellPrice record = (ResellPrice) sqlMapClient.queryForObject(
				"resell_price.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public int updateByExampleSelective(ResellPrice record,
			ResellPriceExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"resell_price.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public int updateByExample(ResellPrice record, ResellPriceExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"resell_price.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public int updateByPrimaryKeySelective(ResellPrice record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"resell_price.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	public int updateByPrimaryKey(ResellPrice record) throws SQLException {
		int rows = sqlMapClient.update(
				"resell_price.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table resell_price
	 * @ibatorgenerated  Sun Jan 27 21:49:32 CST 2013
	 */
	private static class UpdateByExampleParms extends ResellPriceExample {
		private Object record;

		public UpdateByExampleParms(Object record, ResellPriceExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}