package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.Route;
import com.ppsea.ds.data.model.RouteExample;
import java.sql.SQLException;
import java.util.List;

public interface RouteDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    int countByExample(RouteExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    int deleteByExample(RouteExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    Integer insert(Route record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    Integer insertSelective(Route record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    List selectByExample(RouteExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    Route selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    int updateByExampleSelective(Route record, RouteExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    int updateByExample(Route record, RouteExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    int updateByPrimaryKeySelective(Route record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table route
     *
     * @ibatorgenerated Wed Apr 07 13:15:14 CST 2010
     */
    int updateByPrimaryKey(Route record) throws SQLException;
}