package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.SectTitle;
import com.ppsea.ds.data.model.SectTitleExample;
import java.sql.SQLException;
import java.util.List;

public class SectTitleDAOImpl implements SectTitleDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public SectTitleDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public int countByExample(SectTitleExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("sect_title.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public int deleteByExample(SectTitleExample example) throws SQLException {
        int rows = sqlMapClient.delete("sect_title.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        SectTitle key = new SectTitle();
        key.setId(id);
        int rows = sqlMapClient.delete("sect_title.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public Integer insert(SectTitle record) throws SQLException {
        Object newKey = sqlMapClient.insert("sect_title.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public Integer insertSelective(SectTitle record) throws SQLException {
        Object newKey = sqlMapClient.insert("sect_title.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public List selectByExample(SectTitleExample example) throws SQLException {
        List list = sqlMapClient.queryForList("sect_title.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public SectTitle selectByPrimaryKey(Integer id) throws SQLException {
        SectTitle key = new SectTitle();
        key.setId(id);
        SectTitle record = (SectTitle) sqlMapClient.queryForObject("sect_title.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public int updateByExampleSelective(SectTitle record, SectTitleExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sect_title.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public int updateByExample(SectTitle record, SectTitleExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("sect_title.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public int updateByPrimaryKeySelective(SectTitle record) throws SQLException {
        int rows = sqlMapClient.update("sect_title.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public int updateByPrimaryKey(SectTitle record) throws SQLException {
        int rows = sqlMapClient.update("sect_title.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private static class UpdateByExampleParms extends SectTitleExample {
        private Object record;

        public UpdateByExampleParms(Object record, SectTitleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}