package com.ppsea.ds.data.dao;

import com.ppsea.ds.data.model.SectTitle;
import com.ppsea.ds.data.model.SectTitleExample;
import java.sql.SQLException;
import java.util.List;

public interface SectTitleDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    int countByExample(SectTitleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    int deleteByExample(SectTitleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    Integer insert(SectTitle record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    Integer insertSelective(SectTitle record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    List selectByExample(SectTitleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    SectTitle selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    int updateByExampleSelective(SectTitle record, SectTitleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    int updateByExample(SectTitle record, SectTitleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    int updateByPrimaryKeySelective(SectTitle record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sect_title
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    int updateByPrimaryKey(SectTitle record) throws SQLException;
}