package com.ppsea.ds.data.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.ppsea.ds.data.model.SpecBuff;
import com.ppsea.ds.data.model.SpecBuffExample;
import java.sql.SQLException;
import java.util.List;

public class SpecBuffDAOImpl implements SpecBuffDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public SpecBuffDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public int countByExample(SpecBuffExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"spec_buff.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public int deleteByExample(SpecBuffExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"spec_buff.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		SpecBuff key = new SpecBuff();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"spec_buff.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public Integer insert(SpecBuff record) throws SQLException {
		Object newKey = sqlMapClient.insert("spec_buff.ibatorgenerated_insert",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public Integer insertSelective(SpecBuff record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"spec_buff.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public List selectByExample(SpecBuffExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"spec_buff.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public SpecBuff selectByPrimaryKey(Integer id) throws SQLException {
		SpecBuff key = new SpecBuff();
		key.setId(id);
		SpecBuff record = (SpecBuff) sqlMapClient.queryForObject(
				"spec_buff.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public int updateByExampleSelective(SpecBuff record, SpecBuffExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"spec_buff.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public int updateByExample(SpecBuff record, SpecBuffExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"spec_buff.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public int updateByPrimaryKeySelective(SpecBuff record) throws SQLException {
		int rows = sqlMapClient
				.update("spec_buff.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	public int updateByPrimaryKey(SpecBuff record) throws SQLException {
		int rows = sqlMapClient.update(
				"spec_buff.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table spec_buff
	 * @ibatorgenerated  Thu Dec 27 01:02:12 CST 2012
	 */
	private static class UpdateByExampleParms extends SpecBuffExample {
		private Object record;

		public UpdateByExampleParms(Object record, SpecBuffExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}