package com.ppsea.ds.data.model;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import com.ppsea.ds.data.BaseObject;

public class CityFacility extends BaseObject implements Comparable<CityFacility>{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.city_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Integer cityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Integer facilityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.pkable
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Boolean pkable;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.alias
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private String alias;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.description
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.east_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Integer eastCityFacilityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.south_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Integer southCityFacilityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.west_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Integer westCityFacilityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.north_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private Integer northCityFacilityId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column city_facility.coordinate
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    private String coordinate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.id
     *
     * @return the value of city_facility.id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.id
     *
     * @param id the value for city_facility.id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.city_id
     *
     * @return the value of city_facility.city_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.city_id
     *
     * @param cityId the value for city_facility.city_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.facility_id
     *
     * @return the value of city_facility.facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.facility_id
     *
     * @param facilityId the value for city_facility.facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setFacilityId(Integer facilityId) {
        this.facilityId = facilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.pkable
     *
     * @return the value of city_facility.pkable
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Boolean getPkable() {
        return pkable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.pkable
     *
     * @param pkable the value for city_facility.pkable
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setPkable(Boolean pkable) {
        this.pkable = pkable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.alias
     *
     * @return the value of city_facility.alias
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.alias
     *
     * @param alias the value for city_facility.alias
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.description
     *
     * @return the value of city_facility.description
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.description
     *
     * @param description the value for city_facility.description
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.east_city_facility_id
     *
     * @return the value of city_facility.east_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer getEastCityFacilityId() {
        return eastCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.east_city_facility_id
     *
     * @param eastCityFacilityId the value for city_facility.east_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setEastCityFacilityId(Integer eastCityFacilityId) {
        this.eastCityFacilityId = eastCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.south_city_facility_id
     *
     * @return the value of city_facility.south_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer getSouthCityFacilityId() {
        return southCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.south_city_facility_id
     *
     * @param southCityFacilityId the value for city_facility.south_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setSouthCityFacilityId(Integer southCityFacilityId) {
        this.southCityFacilityId = southCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.west_city_facility_id
     *
     * @return the value of city_facility.west_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer getWestCityFacilityId() {
        return westCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.west_city_facility_id
     *
     * @param westCityFacilityId the value for city_facility.west_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setWestCityFacilityId(Integer westCityFacilityId) {
        this.westCityFacilityId = westCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.north_city_facility_id
     *
     * @return the value of city_facility.north_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public Integer getNorthCityFacilityId() {
        return northCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.north_city_facility_id
     *
     * @param northCityFacilityId the value for city_facility.north_city_facility_id
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setNorthCityFacilityId(Integer northCityFacilityId) {
        this.northCityFacilityId = northCityFacilityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column city_facility.coordinate
     *
     * @return the value of city_facility.coordinate
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public String getCoordinate() {
        return coordinate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column city_facility.coordinate
     *
     * @param coordinate the value for city_facility.coordinate
     *
     * @ibatorgenerated Mon Mar 29 14:48:02 CST 2010
     */
    public void setCoordinate(String coordinate) {
        this.coordinate = coordinate;
    }
    
    
    /**********************************************************************************
     * custom code block
     * 
     * ********************************************************************************/
	private transient List<CityFacility> destinations = new ArrayList<CityFacility>();
	
    private transient Map<Integer, Integer> players = new ConcurrentHashMap<Integer, Integer>();
    private transient List<Integer> onlinePlayers = new LinkedList<Integer>();
    private transient City city;
    private transient Facility facility;
    private transient String location;
    
	private transient List<Event> events = new ArrayList<Event>();
	
	private transient List<Action> actions = new ArrayList<Action>();
	
	public int compareTo(CityFacility o) {
		return facility.getSort() -o.getFacility().getSort();
	}
    
    public void removePlayer(int pid){
    	players.remove(pid);
    }
    
	public void addPlayer(int pid){
		players.put(pid, pid);
	}

	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Facility getFacility() {
		return facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public String getLocation() {
		if(location == null){
			location = city.getName()+alias;
		}
		return location;
	}

	public List<CityFacility> getDestinations() {
		return destinations;
	}

	public void setDestinations(List<CityFacility> destinations) {
		this.destinations = destinations;
	}
	
	public List<Event> getEvents() {
		return events;
	}

	public void setEvents(List<Event> events) {
		this.events = events;
	}

	private transient long lastUpdateTime = 0;
	public List<Integer> getOnlinePlayers(){
		//TODO 降低更新频率
		if(System.currentTimeMillis() - lastUpdateTime < 0){
			return onlinePlayers;
		}
		
		lastUpdateTime = System.currentTimeMillis();
		onlinePlayers.clear();
		
		for(Integer pid:players.values()){
			onlinePlayers.add(pid);
		}
		return onlinePlayers;
	}

	public List<Action> getActions() {
		return actions;
	}

	public void setActions(List<Action> actions) {
		this.actions = actions;
	}
}