package com.ppsea.ds.data.model;

import com.ppsea.ds.data.BaseObject;

public class EventExtraDesc extends BaseObject {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column event_extra_desc.id
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column event_extra_desc.event_extra_id
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    private Integer eventExtraId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column event_extra_desc.probability
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    private Integer probability;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column event_extra_desc.description
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column event_extra_desc.id
     *
     * @return the value of event_extra_desc.id
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column event_extra_desc.id
     *
     * @param id the value for event_extra_desc.id
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column event_extra_desc.event_extra_id
     *
     * @return the value of event_extra_desc.event_extra_id
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public Integer getEventExtraId() {
        return eventExtraId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column event_extra_desc.event_extra_id
     *
     * @param eventExtraId the value for event_extra_desc.event_extra_id
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public void setEventExtraId(Integer eventExtraId) {
        this.eventExtraId = eventExtraId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column event_extra_desc.probability
     *
     * @return the value of event_extra_desc.probability
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public Integer getProbability() {
        return probability;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column event_extra_desc.probability
     *
     * @param probability the value for event_extra_desc.probability
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public void setProbability(Integer probability) {
        this.probability = probability;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column event_extra_desc.description
     *
     * @return the value of event_extra_desc.description
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column event_extra_desc.description
     *
     * @param description the value for event_extra_desc.description
     *
     * @abatorgenerated Thu May 14 08:54:55 CST 2009
     */
    public void setDescription(String description) {
        this.description = description;
    }
}