package com.ppsea.ds.data.model;

import java.util.ArrayList;
import java.util.List;

import com.ppsea.ds.data.BaseObject;

public class EventResult extends BaseObject {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column event_result.id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column event_result.description
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	private String description;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column event_result.item_id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	private Integer itemId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column event_result.item_count
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	private Integer itemCount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column event_result.event_id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	private Integer eventId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column event_result.id
	 * @return  the value of event_result.id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column event_result.id
	 * @param id  the value for event_result.id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column event_result.description
	 * @return  the value of event_result.description
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column event_result.description
	 * @param description  the value for event_result.description
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column event_result.item_id
	 * @return  the value of event_result.item_id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public Integer getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column event_result.item_id
	 * @param itemId  the value for event_result.item_id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column event_result.item_count
	 * @return  the value of event_result.item_count
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public Integer getItemCount() {
		return itemCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column event_result.item_count
	 * @param itemCount  the value for event_result.item_count
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public void setItemCount(Integer itemCount) {
		this.itemCount = itemCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column event_result.event_id
	 * @return  the value of event_result.event_id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public Integer getEventId() {
		return eventId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column event_result.event_id
	 * @param eventId  the value for event_result.event_id
	 * @abatorgenerated  Sun Mar 08 21:00:49 CST 2009
	 */
	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}
	
	private List<EventResultPlayer> erPlayers = null;
	
	private List<EventResultItem> erItems = null;
	
	private List<EventResultSkill> erSkills = null;

	public List<EventResultPlayer> getErPlayers() {
		return erPlayers;
	}

	public void setErPlayers(List<EventResultPlayer> erPlayers) {
		if(erPlayers == null) erPlayers = new ArrayList<EventResultPlayer>();
		
		this.erPlayers = erPlayers;
	}

	public List<EventResultItem> getErItems() {
		return erItems;
	}

	public void setErItems(List<EventResultItem> erItems) {
		if(erItems == null) erItems = new ArrayList<EventResultItem>();
		
		this.erItems = erItems;
	}

	public List<EventResultSkill> getErSkills() {
		return erSkills;
	}

	public void setErSkills(List<EventResultSkill> erSkills) {
		if(erSkills == null) erSkills = new ArrayList<EventResultSkill>();
		
		this.erSkills = erSkills;
	}
	
}