package com.ppsea.ds.data.model;

import java.util.List;

import com.ppsea.ds.data.BaseObject;

public class Goods extends BaseObject {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.id
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.name
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.description
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.price
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Integer price;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.gold
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Integer gold;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.is_validate
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Boolean isValidate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.display_order
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Integer displayOrder;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.min_amount
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Integer minAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.max_amount
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Integer maxAmount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.type
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Byte type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column goods.buy_type
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    private Integer buyType;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.gold
     *
     * @return the value of goods.gold
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.gold
     *
     * @param gold the value for goods.gold
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setGold(Integer gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.is_validate
     *
     * @return the value of goods.is_validate
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Boolean getIsValidate() {
        return isValidate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.is_validate
     *
     * @param isValidate the value for goods.is_validate
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setIsValidate(Boolean isValidate) {
        this.isValidate = isValidate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.display_order
     *
     * @return the value of goods.display_order
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.display_order
     *
     * @param displayOrder the value for goods.display_order
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.min_amount
     *
     * @return the value of goods.min_amount
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Integer getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.min_amount
     *
     * @param minAmount the value for goods.min_amount
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setMinAmount(Integer minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.max_amount
     *
     * @return the value of goods.max_amount
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Integer getMaxAmount() {
        return maxAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.max_amount
     *
     * @param maxAmount the value for goods.max_amount
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setMaxAmount(Integer maxAmount) {
        this.maxAmount = maxAmount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.type
     *
     * @return the value of goods.type
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.type
     *
     * @param type the value for goods.type
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column goods.buy_type
     *
     * @return the value of goods.buy_type
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public Integer getBuyType() {
        return buyType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column goods.buy_type
     *
     * @param buyType the value for goods.buy_type
     *
     * @abatorgenerated Wed Apr 21 10:01:15 CST 2010
     */
    public void setBuyType(Integer buyType) {
        this.buyType = buyType;
    }
    
	private transient List<GoodsItem> goodsItems;

	public List<GoodsItem> getGoodsItems() {
		return goodsItems;
	}
	public void setGoodsItems(List<GoodsItem> goodsItems) {
		this.goodsItems = goodsItems;
	}

	private int room;
	public int getRoom() {
		return room;
	}
	public void setRoom(int room) {
		this.room = room;
	}    
}