package com.ppsea.ds.data.model;

import java.util.ArrayList;
import java.util.List;

import com.ppsea.ds.data.BaseObject;

public class ItemDecompose extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.id
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.color
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private Integer color;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.item_level_min
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private Integer itemLevelMin;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.item_level_max
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private Integer itemLevelMax;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.copper
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private Integer copper;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.gold
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private Integer gold;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.item_num
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private String itemNum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column item_decompose.start_level
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	private Integer startLevel;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.id
	 * @return  the value of item_decompose.id
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.id
	 * @param id  the value for item_decompose.id
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.color
	 * @return  the value of item_decompose.color
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer getColor() {
		return color;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.color
	 * @param color  the value for item_decompose.color
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setColor(Integer color) {
		this.color = color;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.item_level_min
	 * @return  the value of item_decompose.item_level_min
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer getItemLevelMin() {
		return itemLevelMin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.item_level_min
	 * @param itemLevelMin  the value for item_decompose.item_level_min
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setItemLevelMin(Integer itemLevelMin) {
		this.itemLevelMin = itemLevelMin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.item_level_max
	 * @return  the value of item_decompose.item_level_max
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer getItemLevelMax() {
		return itemLevelMax;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.item_level_max
	 * @param itemLevelMax  the value for item_decompose.item_level_max
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setItemLevelMax(Integer itemLevelMax) {
		this.itemLevelMax = itemLevelMax;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.copper
	 * @return  the value of item_decompose.copper
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer getCopper() {
		return copper;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.copper
	 * @param copper  the value for item_decompose.copper
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setCopper(Integer copper) {
		this.copper = copper;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.gold
	 * @return  the value of item_decompose.gold
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer getGold() {
		return gold;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.gold
	 * @param gold  the value for item_decompose.gold
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setGold(Integer gold) {
		this.gold = gold;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.item_num
	 * @return  the value of item_decompose.item_num
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public String getItemNum() {
		return itemNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.item_num
	 * @param itemNum  the value for item_decompose.item_num
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setItemNum(String itemNum) {
		this.itemNum = itemNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column item_decompose.start_level
	 * @return  the value of item_decompose.start_level
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public Integer getStartLevel() {
		return startLevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column item_decompose.start_level
	 * @param startLevel  the value for item_decompose.start_level
	 * @ibatorgenerated  Sun Jan 20 23:00:46 CST 2013
	 */
	public void setStartLevel(Integer startLevel) {
		this.startLevel = startLevel;
	}

	/**
	 * 分解可以得到的道
	 */
	private List<ItemVo> itemVos = new ArrayList<ItemVo>();

	public List<ItemVo> getItemVos() {
		return itemVos;
	}

	public void setItemVos(List<ItemVo> itemVos) {
		this.itemVos = itemVos;
	}
}