package com.ppsea.ds.data.model;

import com.ppsea.ds.data.BaseObject;
import com.ppsea.ds.data.Constants;
import com.ppsea.ds.manager.MissionMG;

public class MissionCondition extends BaseObject implements Comparable{
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.player_level
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer playerLevel;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.player_fame
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer playerFame;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.bonus_gold
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer bonusGold;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.target_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer targetId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.issuer_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer issuerId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.hunter_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer hunterId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.description
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private String description;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.player_mission_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer playerMissionId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.city_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer cityId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.issuer_name
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private String issuerName;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.target_name
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private String targetName;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.max_player
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer maxPlayer;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.start
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer start;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column mission_condition.completed
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	private Integer completed;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.id
	 * 
	 * @return the value of mission_condition.id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.id
	 * 
	 * @param id
	 *            the value for mission_condition.id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.player_level
	 * 
	 * @return the value of mission_condition.player_level
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getPlayerLevel() {
		return playerLevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.player_level
	 * 
	 * @param playerLevel
	 *            the value for mission_condition.player_level
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setPlayerLevel(Integer playerLevel) {
		this.playerLevel = playerLevel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.player_fame
	 * 
	 * @return the value of mission_condition.player_fame
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getPlayerFame() {
		return playerFame;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.player_fame
	 * 
	 * @param playerFame
	 *            the value for mission_condition.player_fame
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setPlayerFame(Integer playerFame) {
		this.playerFame = playerFame;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.bonus_gold
	 * 
	 * @return the value of mission_condition.bonus_gold
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getBonusGold() {
		return bonusGold;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.bonus_gold
	 * 
	 * @param bonusGold
	 *            the value for mission_condition.bonus_gold
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setBonusGold(Integer bonusGold) {
		this.bonusGold = bonusGold;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.target_id
	 * 
	 * @return the value of mission_condition.target_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getTargetId() {
		return targetId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.target_id
	 * 
	 * @param targetId
	 *            the value for mission_condition.target_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setTargetId(Integer targetId) {
		this.targetId = targetId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.issuer_id
	 * 
	 * @return the value of mission_condition.issuer_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getIssuerId() {
		return issuerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.issuer_id
	 * 
	 * @param issuerId
	 *            the value for mission_condition.issuer_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setIssuerId(Integer issuerId) {
		this.issuerId = issuerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.hunter_id
	 * 
	 * @return the value of mission_condition.hunter_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getHunterId() {
		return hunterId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.hunter_id
	 * 
	 * @param hunterId
	 *            the value for mission_condition.hunter_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setHunterId(Integer hunterId) {
		this.hunterId = hunterId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.description
	 * 
	 * @return the value of mission_condition.description
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.description
	 * 
	 * @param description
	 *            the value for mission_condition.description
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.player_mission_id
	 * 
	 * @return the value of mission_condition.player_mission_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getPlayerMissionId() {
		return playerMissionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.player_mission_id
	 * 
	 * @param playerMissionId
	 *            the value for mission_condition.player_mission_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setPlayerMissionId(Integer playerMissionId) {
		this.playerMissionId = playerMissionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.city_id
	 * 
	 * @return the value of mission_condition.city_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.city_id
	 * 
	 * @param cityId
	 *            the value for mission_condition.city_id
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.issuer_name
	 * 
	 * @return the value of mission_condition.issuer_name
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public String getIssuerName() {
		return issuerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.issuer_name
	 * 
	 * @param issuerName
	 *            the value for mission_condition.issuer_name
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setIssuerName(String issuerName) {
		this.issuerName = issuerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.target_name
	 * 
	 * @return the value of mission_condition.target_name
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public String getTargetName() {
		return targetName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.target_name
	 * 
	 * @param targetName
	 *            the value for mission_condition.target_name
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setTargetName(String targetName) {
		this.targetName = targetName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.max_player
	 * 
	 * @return the value of mission_condition.max_player
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getMaxPlayer() {
		return maxPlayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.max_player
	 * 
	 * @param maxPlayer
	 *            the value for mission_condition.max_player
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setMaxPlayer(Integer maxPlayer) {
		this.maxPlayer = maxPlayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.start
	 * 
	 * @return the value of mission_condition.start
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getStart() {
		return start;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.start
	 * 
	 * @param start
	 *            the value for mission_condition.start
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setStart(Integer start) {
		this.start = start;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column mission_condition.completed
	 * 
	 * @return the value of mission_condition.completed
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public Integer getCompleted() {
		return completed;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column mission_condition.completed
	 * 
	 * @param completed
	 *            the value for mission_condition.completed
	 * 
	 * @ibatorgenerated Mon May 31 09:42:06 CST 2010
	 */
	public void setCompleted(Integer completed) {
		this.completed = completed;
	}

	private static final long serialVersionUID = 1L;

	public static final String TABLE_NAME = "mission_condition";

	private String dialog = null;

	private int left;

	/**
	 * @return the left
	 */
	public int getLeft() {
		left = this.maxPlayer.intValue()-this.completed.intValue()-MissionMG.instance.getTakedMissionConditions(this.getId()).size();
		if (left < 0) {
			left = 0;
		}
		return left;
	}

	public MissionCondition() {
		this.playerLevel = Constants.HUNT_LEVEL_MIN;
		this.bonusGold = Constants.HUNT_BONUS_GOLD;
		this.completed = 0;
	}

	public Object clone() {
		try {
			return super.clone();
		} catch (CloneNotSupportedException e) {
			return new MissionCondition();
		}
	}

	public String getDialog() {
		return dialog;
	}

	public void setDialog(String dialog) {
		this.dialog = dialog;
	}

	/**
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 */
	public int compareTo(Object o) {
		MissionCondition mc = (MissionCondition)o;
		int ov = this.getBonusGold().intValue();
		int om = this.getMaxPlayer().intValue();
		int tv = mc.getBonusGold().intValue();
		int tm = mc.getMaxPlayer().intValue();
		if (ov/om >= tv/tm) {
			return -1;
		} else {
			return 1;
		}
	}
}