package com.ppsea.ds.data.model;

public class MissionPre {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mission_pre.id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mission_pre.from_mission_id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    private Integer fromMissionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mission_pre.to_mission_id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    private Integer toMissionId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mission_pre.id
     *
     * @return the value of mission_pre.id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mission_pre.id
     *
     * @param id the value for mission_pre.id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mission_pre.from_mission_id
     *
     * @return the value of mission_pre.from_mission_id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    public Integer getFromMissionId() {
        return fromMissionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mission_pre.from_mission_id
     *
     * @param fromMissionId the value for mission_pre.from_mission_id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    public void setFromMissionId(Integer fromMissionId) {
        this.fromMissionId = fromMissionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mission_pre.to_mission_id
     *
     * @return the value of mission_pre.to_mission_id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    public Integer getToMissionId() {
        return toMissionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mission_pre.to_mission_id
     *
     * @param toMissionId the value for mission_pre.to_mission_id
     *
     * @abatorgenerated Sun Dec 21 16:00:47 CST 2008
     */
    public void setToMissionId(Integer toMissionId) {
        this.toMissionId = toMissionId;
    }
}