package com.ppsea.ds.data.model;

import com.ppsea.ds.data.BaseObject;
import com.ppsea.ds.data.Constants;

public class PlayerItemUsing extends BaseObject {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column player_item_using.id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	private Integer id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column player_item_using.player_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	private Integer playerId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column player_item_using.item_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	private Integer itemId;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column player_item_using.expire_time
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	private Integer expireTime;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column player_item_using.pet_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	private Integer petId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column player_item_using.id
	 * 
	 * @return the value of player_item_using.id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column player_item_using.id
	 * 
	 * @param id
	 *            the value for player_item_using.id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column player_item_using.player_id
	 * 
	 * @return the value of player_item_using.player_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public Integer getPlayerId() {
		return playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column player_item_using.player_id
	 * 
	 * @param playerId
	 *            the value for player_item_using.player_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column player_item_using.item_id
	 * 
	 * @return the value of player_item_using.item_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public Integer getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column player_item_using.item_id
	 * 
	 * @param itemId
	 *            the value for player_item_using.item_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column player_item_using.expire_time
	 * 
	 * @return the value of player_item_using.expire_time
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public Integer getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column player_item_using.expire_time
	 * 
	 * @param expireTime
	 *            the value for player_item_using.expire_time
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public void setExpireTime(Integer expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column player_item_using.pet_id
	 * 
	 * @return the value of player_item_using.pet_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public Integer getPetId() {
		return petId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column player_item_using.pet_id
	 * 
	 * @param petId
	 *            the value for player_item_using.pet_id
	 * 
	 * @ibatorgenerated Tue May 11 10:45:09 CST 2010
	 */
	public void setPetId(Integer petId) {
		this.petId = petId;
	}

	private Item item;

	private String leftStr;

	public int getLeft() {

		int left = expireTime - (int) (System.currentTimeMillis() / 1000);
		return left;
	}

	public String getLeftStr() {

		int left = getLeft();
		leftStr = createTimeStr(left);
		return leftStr;
	}

	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	/**
	 * seconds.
	 * 
	 * @param left
	 */
	private static String createTimeStr(int left) {
		if (left <= 0) {
			return Constants.LI_EXPIRED;
		}
		StringBuilder sb = new StringBuilder(12);
		int minute = 60;
		int hour = 60 * minute;
		int h = left / hour;
		if (h > 0) {
			sb.append(h).append(Constants.LI_HOUR);
			left = left % hour;
		}
		int m = left / minute;
		if (m > 0) {
			sb.append(m).append(Constants.LI_MINUTE);
			left = left % minute;
		}
		if (left > 0) {
			sb.append(left).append(Constants.LI_SECOND);
		}
		sb.append(Constants.LI_OTHER);
		return sb.toString();
	}

	public static void main(String[] args) {
		System.out.println(createTimeStr(1));
		System.out.println(createTimeStr(60));
		System.out.println(createTimeStr(0));
		System.out.println(createTimeStr(60 * 60));
		System.out.println(createTimeStr(60 * 60 + 1));
		System.out.println(createTimeStr(60 * 60 * 60 + 63));

	}
}