package com.ppsea.ds.data.model;

import com.ppsea.ds.data.BaseObject;
import java.util.Date;

public class PlayerPromote extends BaseObject {

	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_promote.id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private Integer id;
	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_promote.player_id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private Integer playerId;
	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_promote.belonged_player_id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private Integer belongedPlayerId;
	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_promote.bonus
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private Integer bonus;
	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_promote.create_date
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private Date createDate;
	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_promote.points
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private Integer points;
	/**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column player_promote.last_exchange_points_date
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    private Date lastExchangePointsDate;

	/**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_promote.id
     * @return  the value of player_promote.id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Integer getId() {
	    return id;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_promote.id
     * @param id  the value for player_promote.id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public void setId(Integer id) {
	    this.id = id;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_promote.player_id
     * @return  the value of player_promote.player_id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Integer getPlayerId() {
	    return playerId;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_promote.player_id
     * @param playerId  the value for player_promote.player_id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public void setPlayerId(Integer playerId) {
	    this.playerId = playerId;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_promote.belonged_player_id
     * @return  the value of player_promote.belonged_player_id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Integer getBelongedPlayerId() {
	    return belongedPlayerId;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_promote.belonged_player_id
     * @param belongedPlayerId  the value for player_promote.belonged_player_id
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public void setBelongedPlayerId(Integer belongedPlayerId) {
	    this.belongedPlayerId = belongedPlayerId;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_promote.bonus
     * @return  the value of player_promote.bonus
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Integer getBonus() {
	    return bonus;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_promote.bonus
     * @param bonus  the value for player_promote.bonus
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public void setBonus(Integer bonus) {
	    this.bonus = bonus;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_promote.create_date
     * @return  the value of player_promote.create_date
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Date getCreateDate() {
	    return createDate;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_promote.create_date
     * @param createDate  the value for player_promote.create_date
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public void setCreateDate(Date createDate) {
	    this.createDate = createDate;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_promote.points
     * @return  the value of player_promote.points
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Integer getPoints() {
	    return points;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_promote.points
     * @param points  the value for player_promote.points
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public void setPoints(Integer points) {
	    this.points = points;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column player_promote.last_exchange_points_date
     * @return  the value of player_promote.last_exchange_points_date
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public Date getLastExchangePointsDate() {
	    return lastExchangePointsDate;
    }

	/**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column player_promote.last_exchange_points_date
     * @param lastExchangePointsDate  the value for player_promote.last_exchange_points_date
     * @ibatorgenerated  Thu Jan 06 15:19:37 CST 2011
     */
    public void setLastExchangePointsDate(Date lastExchangePointsDate) {
	    this.lastExchangePointsDate = lastExchangePointsDate;
    }
}