package com.ppsea.ds.data.model;

import com.ppsea.ds.data.BaseObject;

public class SectTitle extends BaseObject {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sect_title.id
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sect_title.sect_id
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private Integer sectId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sect_title.sect_level
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private Integer sectLevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sect_title.name
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sect_title.player_level
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private Integer playerLevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sect_title.fame
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    private Integer fame;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sect_title.id
     *
     * @return the value of sect_title.id
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sect_title.id
     *
     * @param id the value for sect_title.id
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sect_title.sect_id
     *
     * @return the value of sect_title.sect_id
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public Integer getSectId() {
        return sectId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sect_title.sect_id
     *
     * @param sectId the value for sect_title.sect_id
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public void setSectId(Integer sectId) {
        this.sectId = sectId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sect_title.sect_level
     *
     * @return the value of sect_title.sect_level
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public Integer getSectLevel() {
        return sectLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sect_title.sect_level
     *
     * @param sectLevel the value for sect_title.sect_level
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public void setSectLevel(Integer sectLevel) {
        this.sectLevel = sectLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sect_title.name
     *
     * @return the value of sect_title.name
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sect_title.name
     *
     * @param name the value for sect_title.name
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sect_title.player_level
     *
     * @return the value of sect_title.player_level
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public Integer getPlayerLevel() {
        return playerLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sect_title.player_level
     *
     * @param playerLevel the value for sect_title.player_level
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public void setPlayerLevel(Integer playerLevel) {
        this.playerLevel = playerLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sect_title.fame
     *
     * @return the value of sect_title.fame
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public Integer getFame() {
        return fame;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sect_title.fame
     *
     * @param fame the value for sect_title.fame
     *
     * @ibatorgenerated Tue May 25 15:24:09 CST 2010
     */
    public void setFame(Integer fame) {
        this.fame = fame;
    }
}