package com.ppsea.ds.data.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SectExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public SectExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	protected SectExample(SectExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sect
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return this;
		}

		public Criteria andNameIn(List values) {
			addCriterion("name in", values, "name");
			return this;
		}

		public Criteria andNameNotIn(List values) {
			addCriterion("name not in", values, "name");
			return this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return this;
		}

		public Criteria andIntroIsNull() {
			addCriterion("intro is null");
			return this;
		}

		public Criteria andIntroIsNotNull() {
			addCriterion("intro is not null");
			return this;
		}

		public Criteria andIntroEqualTo(String value) {
			addCriterion("intro =", value, "intro");
			return this;
		}

		public Criteria andIntroNotEqualTo(String value) {
			addCriterion("intro <>", value, "intro");
			return this;
		}

		public Criteria andIntroGreaterThan(String value) {
			addCriterion("intro >", value, "intro");
			return this;
		}

		public Criteria andIntroGreaterThanOrEqualTo(String value) {
			addCriterion("intro >=", value, "intro");
			return this;
		}

		public Criteria andIntroLessThan(String value) {
			addCriterion("intro <", value, "intro");
			return this;
		}

		public Criteria andIntroLessThanOrEqualTo(String value) {
			addCriterion("intro <=", value, "intro");
			return this;
		}

		public Criteria andIntroLike(String value) {
			addCriterion("intro like", value, "intro");
			return this;
		}

		public Criteria andIntroNotLike(String value) {
			addCriterion("intro not like", value, "intro");
			return this;
		}

		public Criteria andIntroIn(List values) {
			addCriterion("intro in", values, "intro");
			return this;
		}

		public Criteria andIntroNotIn(List values) {
			addCriterion("intro not in", values, "intro");
			return this;
		}

		public Criteria andIntroBetween(String value1, String value2) {
			addCriterion("intro between", value1, value2, "intro");
			return this;
		}

		public Criteria andIntroNotBetween(String value1, String value2) {
			addCriterion("intro not between", value1, value2, "intro");
			return this;
		}

		public Criteria andImgNameIsNull() {
			addCriterion("img_name is null");
			return this;
		}

		public Criteria andImgNameIsNotNull() {
			addCriterion("img_name is not null");
			return this;
		}

		public Criteria andImgNameEqualTo(String value) {
			addCriterion("img_name =", value, "imgName");
			return this;
		}

		public Criteria andImgNameNotEqualTo(String value) {
			addCriterion("img_name <>", value, "imgName");
			return this;
		}

		public Criteria andImgNameGreaterThan(String value) {
			addCriterion("img_name >", value, "imgName");
			return this;
		}

		public Criteria andImgNameGreaterThanOrEqualTo(String value) {
			addCriterion("img_name >=", value, "imgName");
			return this;
		}

		public Criteria andImgNameLessThan(String value) {
			addCriterion("img_name <", value, "imgName");
			return this;
		}

		public Criteria andImgNameLessThanOrEqualTo(String value) {
			addCriterion("img_name <=", value, "imgName");
			return this;
		}

		public Criteria andImgNameLike(String value) {
			addCriterion("img_name like", value, "imgName");
			return this;
		}

		public Criteria andImgNameNotLike(String value) {
			addCriterion("img_name not like", value, "imgName");
			return this;
		}

		public Criteria andImgNameIn(List values) {
			addCriterion("img_name in", values, "imgName");
			return this;
		}

		public Criteria andImgNameNotIn(List values) {
			addCriterion("img_name not in", values, "imgName");
			return this;
		}

		public Criteria andImgNameBetween(String value1, String value2) {
			addCriterion("img_name between", value1, value2, "imgName");
			return this;
		}

		public Criteria andImgNameNotBetween(String value1, String value2) {
			addCriterion("img_name not between", value1, value2, "imgName");
			return this;
		}

		public Criteria andAgainstSectIdIsNull() {
			addCriterion("against_sect_id is null");
			return this;
		}

		public Criteria andAgainstSectIdIsNotNull() {
			addCriterion("against_sect_id is not null");
			return this;
		}

		public Criteria andAgainstSectIdEqualTo(Integer value) {
			addCriterion("against_sect_id =", value, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdNotEqualTo(Integer value) {
			addCriterion("against_sect_id <>", value, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdGreaterThan(Integer value) {
			addCriterion("against_sect_id >", value, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("against_sect_id >=", value, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdLessThan(Integer value) {
			addCriterion("against_sect_id <", value, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdLessThanOrEqualTo(Integer value) {
			addCriterion("against_sect_id <=", value, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdIn(List values) {
			addCriterion("against_sect_id in", values, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdNotIn(List values) {
			addCriterion("against_sect_id not in", values, "againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdBetween(Integer value1, Integer value2) {
			addCriterion("against_sect_id between", value1, value2,
					"againstSectId");
			return this;
		}

		public Criteria andAgainstSectIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("against_sect_id not between", value1, value2,
					"againstSectId");
			return this;
		}

		public Criteria andSubTypeIsNull() {
			addCriterion("sub_type is null");
			return this;
		}

		public Criteria andSubTypeIsNotNull() {
			addCriterion("sub_type is not null");
			return this;
		}

		public Criteria andSubTypeEqualTo(Integer value) {
			addCriterion("sub_type =", value, "subType");
			return this;
		}

		public Criteria andSubTypeNotEqualTo(Integer value) {
			addCriterion("sub_type <>", value, "subType");
			return this;
		}

		public Criteria andSubTypeGreaterThan(Integer value) {
			addCriterion("sub_type >", value, "subType");
			return this;
		}

		public Criteria andSubTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("sub_type >=", value, "subType");
			return this;
		}

		public Criteria andSubTypeLessThan(Integer value) {
			addCriterion("sub_type <", value, "subType");
			return this;
		}

		public Criteria andSubTypeLessThanOrEqualTo(Integer value) {
			addCriterion("sub_type <=", value, "subType");
			return this;
		}

		public Criteria andSubTypeIn(List values) {
			addCriterion("sub_type in", values, "subType");
			return this;
		}

		public Criteria andSubTypeNotIn(List values) {
			addCriterion("sub_type not in", values, "subType");
			return this;
		}

		public Criteria andSubTypeBetween(Integer value1, Integer value2) {
			addCriterion("sub_type between", value1, value2, "subType");
			return this;
		}

		public Criteria andSubTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("sub_type not between", value1, value2, "subType");
			return this;
		}

		public Criteria andHeasNameIsNull() {
			addCriterion("heas_name is null");
			return this;
		}

		public Criteria andHeasNameIsNotNull() {
			addCriterion("heas_name is not null");
			return this;
		}

		public Criteria andHeasNameEqualTo(String value) {
			addCriterion("heas_name =", value, "heasName");
			return this;
		}

		public Criteria andHeasNameNotEqualTo(String value) {
			addCriterion("heas_name <>", value, "heasName");
			return this;
		}

		public Criteria andHeasNameGreaterThan(String value) {
			addCriterion("heas_name >", value, "heasName");
			return this;
		}

		public Criteria andHeasNameGreaterThanOrEqualTo(String value) {
			addCriterion("heas_name >=", value, "heasName");
			return this;
		}

		public Criteria andHeasNameLessThan(String value) {
			addCriterion("heas_name <", value, "heasName");
			return this;
		}

		public Criteria andHeasNameLessThanOrEqualTo(String value) {
			addCriterion("heas_name <=", value, "heasName");
			return this;
		}

		public Criteria andHeasNameLike(String value) {
			addCriterion("heas_name like", value, "heasName");
			return this;
		}

		public Criteria andHeasNameNotLike(String value) {
			addCriterion("heas_name not like", value, "heasName");
			return this;
		}

		public Criteria andHeasNameIn(List values) {
			addCriterion("heas_name in", values, "heasName");
			return this;
		}

		public Criteria andHeasNameNotIn(List values) {
			addCriterion("heas_name not in", values, "heasName");
			return this;
		}

		public Criteria andHeasNameBetween(String value1, String value2) {
			addCriterion("heas_name between", value1, value2, "heasName");
			return this;
		}

		public Criteria andHeasNameNotBetween(String value1, String value2) {
			addCriterion("heas_name not between", value1, value2, "heasName");
			return this;
		}

		public Criteria andAttackIsNull() {
			addCriterion("attack is null");
			return this;
		}

		public Criteria andAttackIsNotNull() {
			addCriterion("attack is not null");
			return this;
		}

		public Criteria andAttackEqualTo(String value) {
			addCriterion("attack =", value, "attack");
			return this;
		}

		public Criteria andAttackNotEqualTo(String value) {
			addCriterion("attack <>", value, "attack");
			return this;
		}

		public Criteria andAttackGreaterThan(String value) {
			addCriterion("attack >", value, "attack");
			return this;
		}

		public Criteria andAttackGreaterThanOrEqualTo(String value) {
			addCriterion("attack >=", value, "attack");
			return this;
		}

		public Criteria andAttackLessThan(String value) {
			addCriterion("attack <", value, "attack");
			return this;
		}

		public Criteria andAttackLessThanOrEqualTo(String value) {
			addCriterion("attack <=", value, "attack");
			return this;
		}

		public Criteria andAttackLike(String value) {
			addCriterion("attack like", value, "attack");
			return this;
		}

		public Criteria andAttackNotLike(String value) {
			addCriterion("attack not like", value, "attack");
			return this;
		}

		public Criteria andAttackIn(List values) {
			addCriterion("attack in", values, "attack");
			return this;
		}

		public Criteria andAttackNotIn(List values) {
			addCriterion("attack not in", values, "attack");
			return this;
		}

		public Criteria andAttackBetween(String value1, String value2) {
			addCriterion("attack between", value1, value2, "attack");
			return this;
		}

		public Criteria andAttackNotBetween(String value1, String value2) {
			addCriterion("attack not between", value1, value2, "attack");
			return this;
		}

		public Criteria andDefenceIsNull() {
			addCriterion("defence is null");
			return this;
		}

		public Criteria andDefenceIsNotNull() {
			addCriterion("defence is not null");
			return this;
		}

		public Criteria andDefenceEqualTo(String value) {
			addCriterion("defence =", value, "defence");
			return this;
		}

		public Criteria andDefenceNotEqualTo(String value) {
			addCriterion("defence <>", value, "defence");
			return this;
		}

		public Criteria andDefenceGreaterThan(String value) {
			addCriterion("defence >", value, "defence");
			return this;
		}

		public Criteria andDefenceGreaterThanOrEqualTo(String value) {
			addCriterion("defence >=", value, "defence");
			return this;
		}

		public Criteria andDefenceLessThan(String value) {
			addCriterion("defence <", value, "defence");
			return this;
		}

		public Criteria andDefenceLessThanOrEqualTo(String value) {
			addCriterion("defence <=", value, "defence");
			return this;
		}

		public Criteria andDefenceLike(String value) {
			addCriterion("defence like", value, "defence");
			return this;
		}

		public Criteria andDefenceNotLike(String value) {
			addCriterion("defence not like", value, "defence");
			return this;
		}

		public Criteria andDefenceIn(List values) {
			addCriterion("defence in", values, "defence");
			return this;
		}

		public Criteria andDefenceNotIn(List values) {
			addCriterion("defence not in", values, "defence");
			return this;
		}

		public Criteria andDefenceBetween(String value1, String value2) {
			addCriterion("defence between", value1, value2, "defence");
			return this;
		}

		public Criteria andDefenceNotBetween(String value1, String value2) {
			addCriterion("defence not between", value1, value2, "defence");
			return this;
		}

		public Criteria andHpIsNull() {
			addCriterion("hp is null");
			return this;
		}

		public Criteria andHpIsNotNull() {
			addCriterion("hp is not null");
			return this;
		}

		public Criteria andHpEqualTo(String value) {
			addCriterion("hp =", value, "hp");
			return this;
		}

		public Criteria andHpNotEqualTo(String value) {
			addCriterion("hp <>", value, "hp");
			return this;
		}

		public Criteria andHpGreaterThan(String value) {
			addCriterion("hp >", value, "hp");
			return this;
		}

		public Criteria andHpGreaterThanOrEqualTo(String value) {
			addCriterion("hp >=", value, "hp");
			return this;
		}

		public Criteria andHpLessThan(String value) {
			addCriterion("hp <", value, "hp");
			return this;
		}

		public Criteria andHpLessThanOrEqualTo(String value) {
			addCriterion("hp <=", value, "hp");
			return this;
		}

		public Criteria andHpLike(String value) {
			addCriterion("hp like", value, "hp");
			return this;
		}

		public Criteria andHpNotLike(String value) {
			addCriterion("hp not like", value, "hp");
			return this;
		}

		public Criteria andHpIn(List values) {
			addCriterion("hp in", values, "hp");
			return this;
		}

		public Criteria andHpNotIn(List values) {
			addCriterion("hp not in", values, "hp");
			return this;
		}

		public Criteria andHpBetween(String value1, String value2) {
			addCriterion("hp between", value1, value2, "hp");
			return this;
		}

		public Criteria andHpNotBetween(String value1, String value2) {
			addCriterion("hp not between", value1, value2, "hp");
			return this;
		}
	}
}