package com.ppsea.ds.data.model;

import com.ppsea.ds.data.BaseObject;

public class Sect extends BaseObject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.id
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.intro
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private String intro;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.img_name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private String imgName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.against_sect_id
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private Integer againstSectId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.sub_type
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private Integer subType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.heas_name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private String heasName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.attack
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private String attack;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.defence
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private String defence;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sect.hp
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	private String hp;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.id
	 * @return  the value of sect.id
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.id
	 * @param id  the value for sect.id
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.name
	 * @return  the value of sect.name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.name
	 * @param name  the value for sect.name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.intro
	 * @return  the value of sect.intro
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.intro
	 * @param intro  the value for sect.intro
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setIntro(String intro) {
		this.intro = intro;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.img_name
	 * @return  the value of sect.img_name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getImgName() {
		return imgName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.img_name
	 * @param imgName  the value for sect.img_name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.against_sect_id
	 * @return  the value of sect.against_sect_id
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public Integer getAgainstSectId() {
		return againstSectId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.against_sect_id
	 * @param againstSectId  the value for sect.against_sect_id
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setAgainstSectId(Integer againstSectId) {
		this.againstSectId = againstSectId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.sub_type
	 * @return  the value of sect.sub_type
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public Integer getSubType() {
		return subType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.sub_type
	 * @param subType  the value for sect.sub_type
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setSubType(Integer subType) {
		this.subType = subType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.heas_name
	 * @return  the value of sect.heas_name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getHeasName() {
		return heasName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.heas_name
	 * @param heasName  the value for sect.heas_name
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setHeasName(String heasName) {
		this.heasName = heasName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.attack
	 * @return  the value of sect.attack
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getAttack() {
		return attack;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.attack
	 * @param attack  the value for sect.attack
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setAttack(String attack) {
		this.attack = attack;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.defence
	 * @return  the value of sect.defence
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getDefence() {
		return defence;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.defence
	 * @param defence  the value for sect.defence
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setDefence(String defence) {
		this.defence = defence;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sect.hp
	 * @return  the value of sect.hp
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public String getHp() {
		return hp;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sect.hp
	 * @param hp  the value for sect.hp
	 * @ibatorgenerated  Mon Dec 24 23:32:54 CST 2012
	 */
	public void setHp(String hp) {
		this.hp = hp;
	}
}